#!/usr/bin/env node
/**
 * Roadmap tooling.
 *
 *   node scripts/roadmap.mjs check     validate the registry (exit 1 on error)
 *   node scripts/roadmap.mjs render    rewrite docs/roadmap/BOARD.md
 *
 * A roadmap in a repo rots the moment it stops matching the code. The guard is
 * that every feature marked `live` has to point at a route or page that really
 * exists — so deleting code without touching the registry fails the build, and
 * claiming something ships that does not is caught the same way.
 *
 * BOARD.md is generated, never hand-edited: the test regenerates it and compares,
 * exactly like the docs-drift gate.
 */
import { existsSync, readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const APP = join(HERE, "..");
// apps/web -> apps -> repo root. Two levels, not one: this script lives inside
// a workspace package, and docs/ sits at the root beside apps/.
const REPO = join(APP, "..", "..");
const DOCS = join(REPO, "docs", "roadmap");

export const REGISTRY_PATH = join(DOCS, "features.json");
export const BOARD_PATH = join(DOCS, "BOARD.md");

export function loadRegistry() {
  return JSON.parse(readFileSync(REGISTRY_PATH, "utf8"));
}

function milestoneIds() {
  const dir = join(DOCS, "milestones");
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => f.split("-")[0]);
}

/** Returns an array of human-readable problems; empty means the registry is sound. */
export function validate(registry = loadRegistry()) {
  const problems = [];
  const seen = new Set();
  const milestones = new Set(milestoneIds());
  const statuses = new Set(Object.keys(registry.statuses));
  const areas = new Set(Object.keys(registry.areas));
  const surfaces = new Set(registry.surfaces);

  for (const f of registry.features) {
    const at = `${f.id} (${f.name})`;

    if (!/^[A-Z]{3,4}-\d{3}$/.test(f.id)) problems.push(`${at}: id must look like AREA-001`);
    if (seen.has(f.id)) problems.push(`${at}: duplicate id`);
    seen.add(f.id);

    if (!areas.has(f.area)) problems.push(`${at}: unknown area "${f.area}"`);
    if (!statuses.has(f.status)) problems.push(`${at}: unknown status "${f.status}"`);
    if (!f.milestone || !milestones.has(f.milestone)) {
      problems.push(`${at}: milestone "${f.milestone}" has no file in docs/roadmap/milestones/`);
    }
    for (const s of f.target?.surfaces ?? []) {
      if (!surfaces.has(s)) problems.push(`${at}: unknown target surface "${s}"`);
    }
    if (f.status === "deprecated" && !f.notes) {
      problems.push(`${at}: deprecated features must say in notes when and how they are removed`);
    }

    // The anti-fiction rule: anything claiming to be reachable must point at code.
    if (f.status === "live" || f.status === "partial") {
      for (const route of f.today?.api ?? []) {
        const file = join(APP, "src", "app", "api", route, "route.ts");
        if (!existsSync(file)) problems.push(`${at}: api route "${route}" does not exist`);
      }
      if (f.today?.web) {
        const page = join(APP, "src", "app", f.today.web, "page.tsx");
        if (!existsSync(page)) problems.push(`${at}: page "${f.today.web}" does not exist`);
      }
      if (!f.today?.api?.length && !f.today?.web) {
        problems.push(`${at}: status is "${f.status}" but it names no route or page`);
      }
    }

    const migrationStates = new Set(Object.keys(registry.migrationStates));
    if (!migrationStates.has(f.migration)) {
      problems.push(`${at}: unknown migration state "${f.migration}"`);
    }
    if (f.status === "planned" && f.migration !== "n/a") {
      problems.push(`${at}: a planned feature has nothing to migrate — use "n/a"`);
    }
    if (f.migration === "done" && f.status === "planned") {
      problems.push(`${at}: cannot be migrated before it exists`);
    }

    if (f.status === "planned" && f.today) {
      problems.push(`${at}: planned features must not claim existing surfaces`);
    }
  }
  return problems;
}

const BAR_WIDTH = 24;

export function render(registry = loadRegistry()) {
  const byStatus = (s) => registry.features.filter((f) => f.status === s);
  const total = registry.features.length;
  const live = byStatus("live").length;
  const partial = byStatus("partial").length;
  const planned = byStatus("planned").length;
  const deprecated = byStatus("deprecated").length;

  const lines = [];
  lines.push("<!-- Generated by scripts/roadmap.mjs — do not edit by hand.");
  lines.push("     Edit docs/roadmap/features.json, then run: npm run roadmap -->");
  lines.push("");
  lines.push("# Delivery board");
  lines.push("");
  const migrated = registry.features.filter((f) => f.migration === "done").length;
  const migrating = registry.features.filter((f) => f.migration === "in-progress").length;
  lines.push(
    `**${total} features** — ${live} live · ${partial} partial · ${planned} planned · ${deprecated} deprecated`,
  );
  lines.push("");
  lines.push(`**Migration** — ${migrated} done · ${migrating} in progress · ${total - migrated - migrating} not started`);
  lines.push("");

  // Milestone view: what each milestone is actually carrying.
  lines.push("## By milestone");
  lines.push("");
  lines.push("Progress measures **migration to the target architecture**, not whether the");
  lines.push("feature exists today. Most of this product already works; almost none of it has moved.");
  lines.push("");
  lines.push("| Milestone | Scope | Delivered | Remaining |");
  lines.push("| --- | ---: | ---: | ---: |");
  const milestones = [...new Set(registry.features.map((f) => f.milestone))].sort();
  for (const m of milestones) {
    const inM = registry.features.filter((f) => f.milestone === m);
    const done = inM.filter((f) => f.migration === "done").length;
    const filled = Math.round((done / inM.length) * BAR_WIDTH);
    const bar = "█".repeat(filled) + "·".repeat(BAR_WIDTH - filled);
    lines.push(`| **${m}** \`${bar}\` | ${inM.length} | ${done} | ${inM.length - done} |`);
  }
  lines.push("");

  // Area view: the product surface, grouped the way a person thinks about it.
  lines.push("## By area");
  lines.push("");
  for (const [area, blurb] of Object.entries(registry.areas)) {
    const inArea = registry.features.filter((f) => f.area === area);
    if (!inArea.length) continue;
    lines.push(`### ${area} — ${blurb}`);
    lines.push("");
    lines.push("| ID | Feature | Today | Migration | Target service | Surfaces | Milestone |");
    lines.push("| --- | --- | --- | --- | --- | --- | --- |");
    for (const f of inArea) {
      const mark = { live: "live", partial: "partial", planned: "planned", deprecated: "deprecated" }[
        f.status
      ];
      const surfaces = (f.target?.surfaces ?? []).join(", ") || "—";
      lines.push(
        `| \`${f.id}\` | ${f.name} | ${mark} | ${f.migration} | \`${f.target?.service ?? "—"}\` | ${surfaces} | ${f.milestone} |`,
      );
    }
    lines.push("");
  }

  lines.push("## Target services");
  lines.push("");
  lines.push("Where each feature lands in the Rust core. A service owning many features");
  lines.push("is a candidate to split; a service owning one is a candidate to merge.");
  lines.push("");
  lines.push("| Service | Features |");
  lines.push("| --- | ---: |");
  const services = {};
  for (const f of registry.features) {
    const s = f.target?.service ?? "—";
    services[s] = (services[s] ?? 0) + 1;
  }
  for (const [s, n] of Object.entries(services).sort((a, b) => b[1] - a[1])) {
    lines.push(`| \`${s}\` | ${n} |`);
  }
  lines.push("");
  return `${lines.join("\n")}\n`;
}

if (process.argv[1] && process.argv[1].endsWith("roadmap.mjs")) {
  const cmd = process.argv[2] ?? "check";
  if (cmd === "check") {
    const problems = validate();
    if (problems.length) {
      console.error(`roadmap: ${problems.length} problem(s)\n` + problems.map((p) => `  - ${p}`).join("\n"));
      process.exit(1);
    }
    console.log("roadmap: OK — every live feature points at code that exists.");
  } else if (cmd === "render") {
    writeFileSync(BOARD_PATH, render());
    console.log(`roadmap: wrote ${BOARD_PATH}`);
  } else {
    console.error(`unknown command "${cmd}" — use check or render`);
    process.exit(1);
  }
}
