import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Basecamper",
  description: "The terms that govern your use of Basecamper.",
};

import { TERMS_VERSION } from "@/lib/constants";

const LAST_UPDATED = "24 August 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-10">
      <h2 className="font-display text-lg uppercase tracking-widest text-stone-100">{title}</h2>
      <div className="mt-3 space-y-3 text-sm leading-relaxed text-stone-400">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 sm:px-6">
      <p className="font-display text-xs uppercase tracking-[0.35em] text-stone-500">Legal</p>
      <h1 className="mt-1 font-display text-4xl uppercase tracking-widest text-stone-100">
        Terms of Service
      </h1>
      <p className="mt-2 font-mono text-xs text-stone-500">
        Last updated: {LAST_UPDATED} · version {TERMS_VERSION}
      </p>

      <Section title="The service">
        <p>
          Basecamper is a platform for discovering adventures, planning trips with an AI assistant,
          and sharing them with a community. By creating an account or using the site you agree to
          these terms and to our{" "}
          <Link href="/privacy" className="text-amber-500 hover:text-amber-400">
            Privacy Policy
          </Link>
          .
        </p>
      </Section>

      <Section title="Adventure safely — important disclaimer">
        <p>
          Adventure travel is inherently risky. Content on Basecamper — including community-posted
          adventures, difficulty grades, gear lists, seasonal guidance, and anything generated by
          the AI trip planner — is provided for inspiration and planning convenience only. It is not
          professional mountain guiding, medical, safety, or travel advice, may be incomplete or out
          of date, and must be independently verified before you rely on it. Conditions change;
          permits, guides, insurance, and honest self-assessment of your own ability are your
          responsibility. You undertake any trip entirely at your own risk.
        </p>
      </Section>

      <Section title="AI-generated content">
        <p>
          The trip planner uses large language models. Its output can be wrong, outdated, or
          unsuitable for your fitness level despite our efforts to make it honest about risk. Verify
          critical details (routes, altitudes, seasons, visas, permits, prices) with authoritative
          sources before booking or travelling.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You must provide accurate information and keep your account secure. You are responsible
          for activity under your account. We may suspend accounts that break these terms or abuse
          the service (including attempts to circumvent rate limits or usage caps).
        </p>
      </Section>

      <Section title="Your content">
        <p>
          You own what you post. By posting you grant Basecamper a non-exclusive, worldwide,
          royalty-free licence to host, display, and distribute that content as part of operating
          and promoting the service. Do not post content that is unlawful, infringing, deceptive
          (e.g. fabricated route information that could endanger others), or abusive. We may remove
          content that violates these rules.
        </p>
      </Section>

      <Section title="Pro subscription">
        <ul className="list-disc space-y-2 pl-5">
          <li>Pro costs £9/month, billed by Stripe, and renews automatically.</li>
          <li>
            Cancel any time; access continues to the end of the paid period. Statutory refund rights
            are unaffected.
          </li>
          <li>Prices may change with at least 30 days&rsquo; notice before your next renewal.</li>
          <li>
            If you add your own OpenAI API key, usage billed by OpenAI under your key is between you
            and OpenAI.
          </li>
        </ul>
      </Section>

      <Section title="Liability">
        <p>
          Nothing in these terms limits liability that cannot be limited by law (including for death
          or personal injury caused by our negligence). Subject to that, Basecamper is provided
          &ldquo;as is&rdquo;; we are not liable for losses arising from reliance on platform
          content, third-party services (flights, operators, payment providers), or events outside
          our reasonable control, and our total liability is limited to the amount you paid us in
          the 12 months before the claim.
        </p>
      </Section>

      <Section title="Changes and termination">
        <p>
          We may update these terms; material changes will be announced on the site with a new
          version date, and continued use after that constitutes acceptance. You can delete your
          account at any time from profile settings, which removes your data as described in the
          Privacy Policy.
        </p>
      </Section>

      <Section title="Governing law & contact">
        <p>
          These terms are governed by the law of England and Wales. Questions:{" "}
          <span className="text-stone-300">hello@basecamper.ai</span>.
        </p>
      </Section>
    </div>
  );
}
