import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const HIGHLIGHTS: Record<string, string[]> = {
  "seed-adventure-761": [
    "Multi-day crossing from Argentine Patagonia into Chile via unmarked backcountry routes",
    "Camp on the windswept shores of Lago del Desierto before the border crossing",
    "Trek through Lenga beech forest carpeted in autumn red and orange",
    "Navigate the Paso del Viento glacier on crampons with a mountain guide",
    "First view of Cerro FitzRoy and the Paine massif from the ridge",
    "Cross the Chilean border on foot and descend to Puerto Natales",
  ],
  "seed-adventure-762": [
    "Race 55 km across Iceland's volcanic highlands linking Landmannalaugar to Þórsmörk",
    "Run across rhyolite ridges streaked in red, green and yellow mineral hues",
    "Descend into the Þórsmörk valley through dense birch scrub and river crossings",
    "Soak in natural hot springs at Landmannalaugar after completing the course",
  ],
  "seed-adventure-763": [
    "Pedal out of Lhasa past the Potala Palace and into the high-altitude plateau",
    "Cross Khamba La pass at 4,794 m with panoramic views of Yamdrok Lake",
    "Descend the Friendship Highway through the Karo La glacier and Gyantse Fortress",
    "Ride through Shigatse and visit Tashilhunpo Monastery — seat of the Panchen Lama",
    "Tackle the Lalung La pass at 5,050 m into Nepal's high Himalayan landscape",
    "Freewheel down to Kodari on the Nepal border through deep river gorges",
  ],
  "seed-adventure-764": [
    "Dog sled across the frozen Longyearbyen fjord under the Arctic winter sky",
    "Navigate by compass across featureless snow plains at temperatures below −30 °C",
    "Overnight in a remote wilderness hut and conduct polar bear patrol at camp",
    "Witness the blue twilight of polar day — two hours of dim light at midday",
    "Cross the Nordenskiöld Land plateau with reindeer herds moving ahead of the sleds",
    "Return by snowmobile convoy along the coastline as the sun grazes the horizon",
  ],
  "seed-adventure-765": [
    "Launch kayaks from Skiathos harbour and paddle toward the deserted islets of Piperi",
    "Land on the uninhabited beach at Agios Petros — no roads, no crowds",
    "Snorkel over Posidonia seagrass meadows sheltering octopus and sea bream",
    "Navigate the narrow channel between Alonnisos and Peristera at dusk",
    "Wild camp on a pine-covered headland above a turquoise cove",
    "Paddle into the sea caves of Gioura with their wild goat population",
  ],
  "seed-adventure-766": [
    "Trek the ancient trade route through the Wakhan Corridor flanked by the Hindu Kush and Pamirs",
    "Stay with Wakhi families in mud-brick homestays and share bread baked on a stone hearth",
    "Cross the Langar junction and follow the Panj River forming the Afghan border",
    "Climb to a plateau with views of the peak of Noshaq — Afghanistan's highest mountain",
    "Pass nomadic Kyrgyz yurt camps on the Little Pamir plateau at 4,000 m",
    "Trek to the base of Zorkul Lake — a high-altitude wetland on the Roof of the World",
  ],
  "seed-adventure-767": [
    "Dive the Navy Pier at Exmouth for giant grouper, turtles and blacktip reef sharks",
    "Snorkel with whale sharks at Tantabiddi — the world's most reliable aggregation site",
    "Explore the coral bommies of Coral Bay's Mandu Creek at low tide",
    "Night dive the Muiron Islands to watch mantis shrimp and sleeping parrotfish",
    "Sail to Turquoise Bay for drift snorkelling along the outer reef edge",
    "Observe manta rays feeding at Manta Sandy on an evening dive",
  ],
  "seed-adventure-768": [
    "Trek the rim of the Quilotoa volcanic crater lake — a vivid turquoise caldera",
    "Descend to the crater floor and kayak across the 3 km wide crater lake",
    "Walk the market trail between Zumbahua and Chugchilán through Andean farmland",
    "Sleep in the hacienda at Isinlivi surrounded by Cotopaxi's snow-capped silhouette",
  ],
  "seed-adventure-769": [
    "Paddle glassy channels between the islands of the Alexander Archipelago near Ketchikan",
    "Watch humpback whales lunge-feed on herring in the narrows at Frederick Sound",
    "Camp on a gravel beach below the LeConte Glacier — the southernmost tidewater glacier in the US",
    "Kayak past a Steller sea lion haul-out and a bald eagle nesting colony",
    "Navigate the tidal rapids at Sergius Narrows — only passable at slack water",
    "Paddle into Tracy Arm Fjord under a canopy of calving glaciers",
  ],
  "seed-adventure-770": [
    "Trek above 4,000 m through Afroalpine moorland dotted with giant lobelias and heather",
    "Spot gelada baboons grazing on the cliff edges of the Geech Abyss",
    "Reach Ras Dashen — Ethiopia's highest summit at 4,550 m — on day five",
    "Walk along sheer 500 m escarpments above the Belegez and Dibi rivers",
    "Visit the village of Debark and the weekly market before the trail begins",
    "Camp under clear Afroalpine skies at 3,600 m with Ibex visible at dawn",
  ],
  "seed-adventure-771": [
    "Skin up from Chamonix's Grands Montets and cross the Col du Chardonnet at 3,323 m",
    "Ski the Vallée Blanche — 20 km of off-piste descending from the Aiguille du Midi",
    "Traverse the Grand Col Ferret into Switzerland under the north face of Mont Blanc",
    "Overnight at the Cabane du Mont Fort hut above Verbier at 2,457 m",
    "Ski the Pigne d'Arolla — a high-altitude summit with 360° views of the Pennine Alps",
    "Final descent to Zermatt with the Matterhorn filling the valley head",
  ],
  "seed-adventure-772": [
    "Pedal bamboo-lined roads through the coffee fincas between Salento and Filandia",
    "Visit a working coffee farm, hand-pick cherries and taste freshly roasted single-origin",
    "Cycle through the Cocora Valley amid towering wax palms — Colombia's national tree",
    "Ride the switchbacks above Manizales with views of the snow-capped Nevado del Ruiz",
    "Descend to the Cauca River valley on cobblestones through banana and plantain groves",
    "Overnight in a restored bahareque farmhouse in the UNESCO Coffee Cultural Landscape",
  ],
  "seed-adventure-773": [
    "Hike through Karen hill tribe villages on the flanks of Doi Inthanon — Thailand's highest peak",
    "Visit the twin chedis of King and Queen at the summit plateau surrounded by montane forest",
    "Trek to the Siriphum Waterfall through a cloud forest of orchids and mosses",
    "Birdwatch at dawn for rare species including the green-tailed sunbird and the ward's trogon",
  ],
  "seed-adventure-774": [
    "Ski from the east coast across the full width of the Greenland Ice Sheet to the west coast",
    "Haul loaded pulks across 500 km of featureless white at altitudes above 2,400 m",
    "Navigate using GPS and compass through complete whiteout conditions",
    "Experience 24-hour Arctic daylight — skiing at midnight under a sun that never sets",
    "Cross the highest point of the ice sheet at 2,850 m with sub-zero winds",
    "Descend to the icecap margin above Kangerlussuaq and celebrate at the Russell Glacier",
  ],
  "seed-adventure-775": [
    "Walk the 540 km Lycian Way from Fethiye to Antalya along limestone coastal cliffs",
    "Swim from the trail into hidden coves accessible only on foot",
    "Explore the Lycian rock tombs cut into the cliffs above Dalyan and Pinara",
    "Camp on the ruins of Olympos — an ancient city half-swallowed by fig trees",
    "Trek past the eternal flames of Chimaera — natural methane vents burning in the hillside",
    "Finish on the walls of ancient Phaselis with its triple harbour below",
  ],
  "seed-adventure-776": [
    "Summit Mount Kinabalu at 4,095 m — Southeast Asia's highest peak — via the Summit Trail",
    "Sleep at Laban Rata Resthouse at 3,270 m and ascend by torchlight for sunrise",
    "Trek through the dipterocarp rainforest of Kinabalu Park — a UNESCO World Heritage Site",
    "Spot pitcher plants, hornbills and Borneo pygmy squirrels on the lower trail",
    "Traverse the lowland rainforest of the Maliau Basin on a multi-day loop",
    "Night walk in Danum Valley to spot clouded leopards, tarsiers and civets",
  ],
  "seed-adventure-777": [
    "Trek four days into the Apurimac Canyon to Choquequirao — the 'Cradle of Gold' Inca citadel",
    "Descend 1,500 m to the Apurimac River on switchbacks with condors circling overhead",
    "Climb through cloud forest to the terraced agricultural platforms of the lower citadel",
    "Reach the main plaza — only accessible on foot, with fewer than 50 visitors per day",
    "Explore the 'llama terraces' — decorated with white stone llama reliefs unique in Inca art",
  ],
  "seed-adventure-778": [
    "Cycle the 1,200 km Shikoku Henro pilgrimage route visiting all 88 Buddhist temples",
    "Ring the bell and chant the sutra at each ohenro temple wearing white pilgrim robes",
    "Ride the rugged Kochi Prefecture coast with the Pacific breaking on sea cliffs below",
    "Climb to Tairyuji — temple 21 — by cable car into the forested mountains of Tokushima",
    "Be welcomed as an o-settai recipient — local families offering food and lodging to pilgrims",
    "Complete the circuit at Okuboji temple 88 and return to Koyasan to pay respects to Kobo Daishi",
  ],
  "seed-adventure-779": [
    "Board a Tundra Buggy on the shores of Hudson Bay and track polar bear dens in early winter",
    "Watch a male polar bear sparring on the frozen Churchill River tidal flats",
    "Walk a baited trap line with scientists from the Churchill Wildlife Management Area",
    "See the Northern Lights reflecting over Hudson Bay on a clear November night",
    "Learn about sea ice dynamics and bear population monitoring at the Churchill Northern Studies Centre",
  ],
  "seed-adventure-780": [
    "Trek through rhododendron forest above Pokhara into the high Mardi Himal valley",
    "Camp at High Camp (4,500 m) with a direct view of Machhapuchchhre's unclimbed south face",
    "Summit the Mardi Himal viewpoint ridge for a panorama of Annapurna I, II, III and Gangapurna",
    "Descend through the dense forest of the Mardi Himal Conservation Area via Low Camp",
    "Spot red panda and Himalayan tahr on the forested lower ridges",
    "Return to Pokhara via Siding village and celebrate with dal bhat lakeside",
  ],
  "seed-adventure-781": [
    "Hike the Sørvágsvatn lake cliff trail — the lake appears to float 100 m above the ocean",
    "Follow the ridge walk to Trælanípa for the iconic cliffside view at sunset",
    "Traverse the basalt columns of Vestmanna sea cliffs on a three-hour coastal hike",
    "Hike to the top of Slættaratindur — the Faroes' highest peak — in mist and wind",
    "Cross the wooden bridge over the sea to the grass-turfed village of Gásadalur",
    "Walk the dramatic ridgeline of Vágar island with puffins nesting on the ledges below",
  ],
  "seed-adventure-782": [
    "Drive the RN7 south from Antananarivo through highlands of rice paddies and zebu cattle",
    "Explore the Avenue of the Baobabs near Morondava — six species unique to Madagascar",
    "Navigate the rough piste to Isalo National Park and hike through red sandstone canyons",
    "Cross the Tropic of Capricorn and descend to the spiny desert of the Mahafaly Plateau",
    "Visit the fishing village of Tulear and snorkel the Ifaty coral reef",
    "Return via the east coast rainforest where ring-tailed lemurs feed in the treetops",
    "Navigate river crossings and mud tracks in the wet season — 4WD essential",
  ],
  "seed-adventure-783": [
    "Climb the via ferrata ladders of the Hochtor — a 2,369 m summit above the Enns Valley",
    "Traverse the Eisenerzer Reichenstein iron-ore peaks on a multi-pitch steel cable route",
    "Overnight in the Hesshütte mountain hut at 1,699 m with Styrian beer and cold cuts",
    "Tackle the Klettersteig at Admonter Reichenstein — rated D/E with vertical cliff sections",
    "Descend via the Johnsbach gorge trail through a narrow limestone ravine",
    "Link three summits above 2,000 m over six days in the Gesäuse National Park",
  ],
  "seed-adventure-784": [
    "Drive from Santiago de Cuba through the Sierra Maestra — birthplace of the Cuban Revolution",
    "Visit Comandancia de La Plata — Fidel Castro's secret jungle headquarters",
    "Swim at the secluded Playa Siboney — a white-sand beach east of Santiago unchanged since the 1950s",
    "Explore the colonial streets of Baracoa — Cuba's oldest city isolated behind the mountains",
    "Taste cocoa-based local cuisine at a palenque — a traditional Afro-Cuban communal farm",
    "Drive the Farallones coastal road — a dirt track cut into the cliffs above the Caribbean",
  ],
  "seed-adventure-785": [
    "Fly by light aircraft to a remote camp on the Skeleton Coast — no roads, no tourists",
    "Track desert-adapted lion prides moving along the dry Hoarusib river bed",
    "Watch a brown hyena scavenging a Cape fur seal carcass on the Atlantic shoreline",
    "Walk with a San tracker through black desert rock — identifying spoor of oryx and jackal",
    "Spot the rare desert elephant herds crossing the gravel plains to find water",
    "Watch the Atlantic fog roll in over the dune sea at dawn from the fly camp",
  ],
  "seed-adventure-786": [
    "Trek between remote Chin villages accessible only on foot — no road, no mobile signal",
    "Observe the last tattooed elders of the Mun (Chin) people in villages near Mindat",
    "Sleep on bamboo-floored guesthouses and eat fermented bamboo shoots and rice wine",
    "Climb to the Chin Hills ridge at 2,500 m for views into the Irrawaddy valley below",
    "Walk through cardamom and ginger plantations and learn about the Chin cultivation cycle",
    "Attend a village elder ceremony and witness the traditional rattan weaving process",
  ],
  "seed-adventure-787": [
    "Cycle the Wild Atlantic Way from Donegal's sea cliffs to the Ring of Kerry",
    "Ride the Dingle Peninsula — 50 km loop past Gallarus Oratory and Mount Brandon",
    "Freewheel the descent from Conor Pass with the Atlantic glittering below",
    "Push up the Healy Pass in Kerry on the county boundary ridge with views to Bantry Bay",
    "Overnight in Clifden — the 'Capital of Connemara' — between the Twelve Bens mountains",
    "Cycle the Malin Head — Ireland's most northerly point — in autumn Atlantic gales",
  ],
  "seed-adventure-788": [
    "Walk Alta Via 1 from Lago di Braies to Belluno — 120 km through the heart of the Dolomites",
    "Camp below the Tre Cime di Lavaredo — three vertical towers of pale dolomite",
    "Cross the Forcella di Lavaredo pass with a direct view of the north faces",
    "Overnight in the Rifugio Fanes in the alpine meadows of the Fanes-Sennes plateau",
    "Traverse the Sella Group and descend into the Val Gardena — a Ladin-speaking valley",
    "Summit the Lagazuoi via the WWI tunnel system blasted through the peak in 1917",
    "End in Belluno and soak the trail-worn legs in the Piave River",
  ],
  "seed-adventure-789": [
    "Glide through the Okavango papyrus channels in a traditional mokoro dugout canoe",
    "Walk the floodplain islands at night searching for hippo and crocodile by spotlight",
    "Track a pride of lions on foot through the Delta's islands with an armed guide",
    "Observe a leopard hunting lechwe antelope from a mokoro in a quiet backwater",
    "Fly into Chief's Island by light aircraft and explore on foot in a private concession",
    "Sleep in a raised canvas tent with elephants grazing twenty metres from the platform",
  ],
  "seed-adventure-790": [
    "Trek into the remote Rolwaling Valley — rarely visited and requiring a special permit",
    "Climb to the Tashi Lapcha pass at 5,755 m — a high-altitude pass with views of Gaurishankar",
    "Camp on glacial moraines below the south face of Rolwaling Himal",
    "Navigate the Drolambau Glacier on crampons and roped together",
    "Overnight in the village of Na — the last inhabited settlement in the valley",
    "Cross into the Khumbu via the Tashi Lapcha and descend to Thame monastery",
  ],
  "seed-adventure-791": [
    "Walk the Rota Vicentina from Porto Covo to Odeceixe — 200 km along Europe's wildest coast",
    "Navigate cliff paths above Atlantic swell on the Fishermen's Trail — used by local sardine fishers",
    "Swim at Praia do Amado — a deserted surf beach below sandstone cliffs",
    "Pass through white-washed villages where cork oaks line the dusty lanes",
    "Spot the resident pod of common dolphins from the Ponta de Sagres sea cliffs",
    "Overnight at an albergue with home-cooked cataplana and local Alentejo wine",
  ],
  "seed-adventure-792": [
    "Ride Criollo horses through the high-altitude vineyards above Mendoza at 1,600 m",
    "Gallop across open pampas to an estancia for an asado lunch with wine from the estate",
    "Trek to the summit of Cerro Pelado on horseback with the Andes snow line above",
    "Camp in the Valle de Uco with the moonlit Aconcagua reflected in the estancia reservoir",
    "Visit a Malbec harvest in March and stomp grapes at a Luján de Cuyo bodega",
    "Attend the gaucho rodeo at the finca and learn the whip-and-boleadora trick roping",
  ],
  "seed-adventure-793": [
    "Dive the Two-Mile Reef at Bazaruto — a pristine 40 m wall draped in soft coral",
    "Snorkel with endangered dugong in the seagrass beds of Banque de Bazaruto",
    "Explore the freshwater lakes of Santa Carolina Island by dhow sailboat",
    "Night dive among fluorescent coral and hunting lionfish off Magaruque",
    "Walk the high dunes of Bazaruto Island and watch flamingo flocks at the lagoon",
    "Dive the Benguerra reef for resident whale sharks from December to March",
  ],
  "seed-adventure-794": [
    "Trek the ancient Tamang trade route through Thuman, Bridim and Gatlang villages",
    "Stay in Tamang homestead guesthouses and learn butter tea making",
    "Visit the Parvati Kund sacred lake at 3,900 m — a pilgrimage site for Tamang Buddhists",
    "Cross the Somdang copper mine plateau at 4,450 m on the Ganesh Himal rim",
    "Observe the Tamang Nyi-Nyak ceremony — a horse and flag festival at the Gosaikunda trail junction",
    "Descend to Syabru Besi through terraced barley fields with Langtang Lirung in view",
  ],
  "seed-adventure-795": [
    "Embark by zodiac from Longyearbyen into the pack ice of Van Keulenfjorden",
    "Hike to the Recherchebreen glacier front — a tide-water glacier actively calving into the fjord",
    "Spot walrus hauled out on ice floes in the fjords of western Svalbard",
    "Trek the tundra plateau above Sassen Valley searching for polar bears and reindeer",
    "Kayak between icebergs in Bellsund fjord in the midnight sun",
    "Visit the ghost town of Grumant — a Soviet coal mining settlement abandoned in 1962",
  ],
  "seed-adventure-796": [
    "Trek from Kaza to Kibber — one of the world's highest villages at 4,200 m",
    "Walk the route above the Pin Valley where snow leopards hunt bharal",
    "Cross the Kunzum La pass at 4,590 m on the roof of Spiti Valley",
    "Visit the 1,000-year-old Tabo Monastery and its ancient clay murals",
    "Trek to the Key Monastery perched on a hill 4,166 m above the Spiti River",
    "Camp on the moonlike Chandratal Lake plateau — turquoise at 4,300 m",
    "Navigate narrow cliff paths between Dankhar and Mane villages",
  ],
  "seed-adventure-797": [
    "Walk the full GR10 from Hendaye on the Atlantic to Banyuls-sur-Mer on the Mediterranean",
    "Cross the Col de la Pierre-St-Martin at 1,760 m into the limestone karst of the Pyrenean interior",
    "Climb the Pic du Midi d'Ossau — the iconic volcanic plug rising above the Pyrenean plateau",
    "Traverse the Cirque de Gavarnie — a UNESCO World Heritage glacial amphitheatre at 1,800 m",
    "Cross the Brèche de Roland — a 40 m gap in the ridge named after Charlemagne's paladin",
    "Overnight in gîtes d'étape in Basque, Béarnais and Catalan villages along the way",
    "Summit Canigou — the sacred mountain of Catalonia — at 2,784 m on the last section",
  ],
  "seed-adventure-798": [
    "Trek into Bwindi Impenetrable Forest — a UNESCO site of 432 km² of montane rainforest",
    "Track the habituated Mubare gorilla family on a full-day forest permit",
    "Spend one hour at close range with a silverback — often within two metres",
    "Walk the Buhoma community trail through banana shambas to a Batwa pygmy village",
    "Bird the forest margins for African green broadbill and the endangered Grauer's swamp warbler",
    "Overnight at a lodge on the forest edge with fireflies and tree hyrax calls at night",
  ],
  "seed-adventure-799": [
    "Fly into Wonder Lake and set up a base camp with Denali filling the northern horizon",
    "Backpack the Toklat River corridor watching grizzly bears fishing for Arctic grayling",
    "Walk the McKinley Bar Trail to the glacial outwash plain with moose in the willows",
    "Camp under the aurora borealis on the tundra with caribou crossing at dawn",
    "Attempt the Primrose Ridge scramble for a 360° panorama of the Alaska Range",
    "Photograph dall sheep on the Cathedral Mountain ridgeline above Polychrome Pass",
  ],
  "seed-adventure-800": [
    "Skin from Hakuba into the Tsugaike Kogen backcountry — ungroomed Japanese powder fields",
    "Ski the Karamatsu Forest — giant cedar groves that filter light into the snow",
    "Ascend to Shirouma-dake at 2,932 m for panoramic views of the Northern Alps",
    "Ski through the Raicho Valley — named after the ptarmigan that live in the snowfields",
    "Overnight in a small mountain hut with local sake and oden hotpot",
    "Take a traditional onsen bath in Nozawa Onsen — a communal bathing village since the 8th century",
  ],
  "seed-adventure-801": [
    "Mount Basotho ponies in Semonkong and ride into the Maluti Highland plateau",
    "Cross the Maletsunyane Falls — Africa's highest single-drop waterfall at 192 m — on horseback",
    "Overnight in Basotho rondavel huts at 3,000 m with no electricity or roads",
    "Ride the 'Roof of Africa' plateau above 3,400 m through snow in winter",
    "Visit the Lesotho Hat — a natural rock arch above the Senqunyane River",
  ],
  "seed-adventure-802": [
    "Walk the GR20 from Calenzana to Conca — 180 km of the most technically demanding long trail in Europe",
    "Scramble the Cirque de la Solitude — a grade-1 scramble on fixed chains and iron rungs",
    "Camp at the Refuge Ciottulu di i Mori in the Fango Valley forest",
    "Summit Monte Cinto at 2,706 m — Corsica's highest peak — on an acclimatisation loop",
    "Traverse the granite needles of the Bavella Aiguilles on the southern section",
    "Swim in the Restonica river gorge pools after eight hours on trail",
    "End at Conca with sore legs, local charcuterie and Corsican chestnut beer",
  ],
  "seed-adventure-803": [
    "Paddle the Bay of Islands between 144 islands of forested volcanic rock",
    "Sea kayak into Piercy Island's cathedral cave — accessible only by boat",
    "Spot bottlenose dolphins and bronze whaler sharks in the outer bay channels",
    "Camp on the beach at Urupukapuka Island — a DOC reserve with no roads",
    "Paddle to the Hole in the Rock — a natural archway through which the ferry passes at high tide",
    "Snorkel the Rainbow Warrior wreck dive at Matauri Bay on a side trip",
  ],
  "seed-adventure-804": [
    "Skin up the Dizin ski area above Tehran — a 3,600 m piste resort turned backcountry gateway",
    "Camp at the Tochal refuge hut at 3,544 m — reached by the world's longest gondola",
    "Ski the north-facing Kandovan couloirs in January powder conditions",
    "Ascend Shemshak's backcountry ridgelines for untracked descent into the Jajrood valley",
    "Warm up with Irani tea, sheep cheese and flatbread at a mountain shepherd shelter",
    "Ski-tour on Mount Damavand's flanks — the world's highest ski mountain at 5,610 m",
  ],
  "seed-adventure-805": [
    "Dive Wolf and Darwin Islands — the only sites in the Galapagos for schooling hammerhead sharks",
    "Drift dive with hundreds of scalloped hammerheads at the Darwin Arch at 30 m depth",
    "Snorkel with sea lions at Kicker Rock — a 150 m volcanic tuff cone off San Cristóbal",
    "Night dive at Cousin's Rock for seahorses, frogfish and Pacific seahorses",
    "Spot whale sharks circling the cleaning stations off Darwin Island",
    "Observe marine iguanas diving to 12 m to graze on algae at Fernandina",
  ],
  "seed-adventure-806": [
    "Sail the Kimberley coast on a liveaboard past the Buccaneer Archipelago's tidal waterfalls",
    "Cruise into the Horizontal Falls — a phenomenon where tidal forces push water through a 10 m gap",
    "Anchor at Montgomery Reef — a 400 km² reef system that emerges from the sea at low tide",
    "Trek up King George Falls — the highest twin-drop waterfall in Western Australia",
    "Dive the coral bommies off Bigge Island with tawny nurse sharks",
    "Helicopter over the Bungle Bungle beehive domes of Purnululu on a day excursion",
  ],
  "seed-adventure-807": [
    "Trek into Volcanoes National Park on the slopes of Karisimbi to find golden monkey troops",
    "Observe a troop of golden monkeys moving through the bamboo zone at 2,800 m",
    "Walk the Musanze Caves — lava tube caverns beneath the Virunga volcanoes",
    "Visit the Dian Fossey memorial at the Karisoke Research Centre site",
    "Learn about Virunga conservation history at the park headquarters in Kinigi",
  ],
  "seed-adventure-808": [
    "Hike the Fjallabak Highland route through the lunar lava fields of the central interior",
    "Camp below Torfajökull — Iceland's largest high-temperature geothermal area",
    "Swim in the emerald hot river at Strútslaug — a natural thermal pool fed by a lava spring",
    "Cross black sand plains between the Mýrdalsjökull and Eyjafjallajökull ice caps",
    "Scramble the obsidian ridges of Laugahraun lava field formed in a 1477 eruption",
    "Descend to Þórsmörk nature reserve through birch scrub carpeted in bilberry",
  ],
  "seed-adventure-809": [
    "Travel by jeep to Bayan-Ölgii — the Kazakh heartland of western Mongolia",
    "Ride with an eagle hunter to the autumn hunting grounds on the Altai foothills",
    "Watch a trained golden eagle stoop on a corsac fox on the open steppe",
    "Stay in a Kazakh ger and eat horse meat stew and airag fermented mare's milk",
    "Attend the Golden Eagle Festival — hundreds of hunters competing with eagles on horseback",
    "Hike to the summit of a Mongolian ice-capped peak with panoramic Altai views",
    "Visit a petroglyphs site — Bronze Age carvings of deer and ibex in the valley walls",
  ],
  "seed-adventure-810": [
    "Climb the Observatory Ridge on Ben Nevis in full winter conditions with axe and crampons",
    "Tackle Tower Ridge — a classic Grade III winter climb with 600 m of mixed snow and ice",
    "Practise self-arrest and crevasse rescue on the upper snowfields of Coire Leis",
    "Navigate the Carn Mòr Dearg Arête in full cloud on compass bearing",
    "Overnight at the CIC Hut below the north face — the highest hut in Britain at 680 m",
    "Watch an ice climber lead the Orion Face — one of Scotland's most famous ice routes",
  ],
  "seed-adventure-811": [
    "Board a slow boat at Manaus and navigate upstream into the Negro River headwaters",
    "Pull into floating villages on stilts — communities with no road connection",
    "Night-canoe the flooded forest listening to caimans and fishing for piranhas by hand-line",
    "Visit the confluence of the Negro and Solimões — the 'Meeting of the Waters' — at Manaus",
    "Spot pink river dolphins surfacing alongside the boat in remote channels",
    "Walk the várzea floodplain with a local biologist identifying medicinal plants",
    "Sleep in a hammock on the boat deck under a sky unpolluted by any artificial light",
  ],
  "seed-adventure-812": [
    "Trek the Picos de Europa from Sotres to the Naranjo de Bulnes — the most iconic limestone spike in Spain",
    "Scramble the final ridge of the Naranjo de Bulnes (Picu Urriellu) — a 2,519 m vertical tower",
    "Cross the Collado Jermoso pass at 2,064 m on the high-level route between massifs",
    "Descend into the Cares Gorge — an 11 km trail carved above a 1,000 m chasm",
    "Overnight at the Refugio Vegarredonda on the plateau with chamois grazing at dusk",
    "End in Arenas de Cabrales and taste the pungent local blue cheese with cider",
  ],
  "seed-adventure-813": [
    "Kayak between the floating gardens of Inle Lake at dawn in a traditional longtail",
    "Cycle the lakeshore villages and visit leg-rowing fishermen at work at Ywama market",
    "Paddle to the Phaung Daw Oo Pagoda — its shrines nearly submerged in lotus blossoms",
    "Hike to the vineyard above Inle and taste Shan red wine produced at Myanmar's only winery",
    "Cycle to the Indein ruins — a field of overgrown stupas rising from the jungle",
    "Watch the weaving of lotus-fibre silk at Inpawkhon — fabric made from lotus stem filaments",
  ],
  "seed-adventure-814": [
    "Trek from Karakol up the Karakol Valley past yak pastures to the Ala-Köl pass at 3,860 m",
    "Camp at the sapphire Ala-Köl lake at 3,500 m — surrounded by glaciated peaks",
    "Cross into the Altin-Arashan Valley — a geothermal hot spring area below Palatka peak",
    "Overnight in yurt camps served with kumis and shashlik",
    "Trek to the Song-Köl plateau — a 3,016 m high-altitude lake with nomadic horse herders",
    "Hike to the base of Khan Tengri at 7,010 m — visible across the Engilchek Glacier",
  ],
  "seed-adventure-815": [
    "Hike the Kīpukapualu trail through a 'sky island' of native koa and ōhiā forest surrounded by lava",
    "Walk the Mauna Ulu lava tube — formed in the 1969–74 eruption — by torchlight",
    "Snorkel Kealakekua Bay marine reserve — one of Hawaiʻi's clearest waters with spinner dolphins",
    "Dive the lava arches off Two Step Beach for Hawaiian monk seals and reef fish",
    "Watch the live lava ocean entry at night from the coastal viewing area",
    "Hike the Crater Rim Drive trail past active steam vents and calderas of Kīlauea",
  ],
  "seed-adventure-816": [
    "Circle the turquoise Ausangate massif — the most sacred Apu (mountain deity) of the Cusco region",
    "Camp at the Ausangate base at 4,850 m with the glacier reflecting at dawn",
    "Trek past the rainbow mountains of Vinicunca — striated in red, orange and purple clay",
    "Cross three passes above 5,000 m including the Palomani Grande at 5,200 m",
    "Overnight in traditional Quechua communities and share chicha with the herders",
  ],
  "seed-adventure-817": [
    "Ski tour across the Hardangervidda — Europe's largest mountain plateau at 1,000–1,200 m",
    "Navigate between DNT mountain huts using map and compass in full Arctic conditions",
    "Ski the classic Finse to Haugesund route on 60 km of packed powder",
    "Pull a pulk loaded with supplies across open country in sub-zero conditions",
    "Watch the Northern Lights shimmer above the plateau from the hut door",
    "Overnight at the historic Finse 1222 hut — used as a filming location for the Hoth scenes in The Empire Strikes Back",
  ],
  "seed-adventure-818": [
    "Trek 500 km through the restricted northern Bhutan wilderness on a 30-day permit",
    "Cross 11 passes above 4,700 m including the Rinchen Zoe La at 5,320 m",
    "Camp at yak-herder summer pastures above 4,000 m and drink salted butter tea",
    "Trek through temperate and alpine meadows between Laya and Lunana — villages with no road access",
    "Spot the endangered black-necked crane in the marshes of Phobjikha Valley on the approach",
    "Navigate the Nikka Chhu river crossings — essential route-finding on the northern section",
    "End at Nikka Chhu with a private audience at a remote monastery",
  ],
  "seed-adventure-819": [
    "Walk game tracks in the Selous / Nyerere National Park — Tanzania's largest protected area",
    "Canoe the Rufiji River past hippo pods and crocodile sandbanks",
    "Track elephant breeding herds on foot through dry miombo woodland with an armed ranger",
    "Night drive and spot African wild dog — one of Tanzania's most endangered predators",
    "Fly-camp beside the Rufiji on a sandbank with only hippo and lion for company",
    "Boat safari to spot the elusive shoebill stork in the reed islands of Stiegler's Gorge",
  ],
  "seed-adventure-820": [
    "Hike the 200 km Transcaucasian Trail section from the Khevsureti highlands to Kazbegi",
    "Sleep in Shatili — a medieval Georgian fortress village built into a canyon wall",
    "Scramble to the summit cross above Gergeti Trinity Church with Kazbegi massif behind",
    "Trek the Truso Valley through sulphur springs and abandoned Ossetian watchtower villages",
    "Cross the 3,338 m Atsunta Pass with a Georgian shepherd and pack horse",
    "Overnight at a remote community guesthouse on churchkhela and Georgian red wine",
  ],
  "seed-adventure-821": [
    "Harness eight Alaskan huskies and mush the frozen Torne River from Kiruna northward",
    "Learn dog sled commands and navigate through the birch forests of Swedish Lapland",
    "Overnight in a reindeer-skin sleeping bag in a Sami kåta (tent) in the forest",
    "Watch the aurora borealis from open tundra at midnight — a full-sky display",
    "Visit a Sami reindeer herder and learn about the annual migration cycle",
  ],
  "seed-adventure-822": [
    "Hike the Jebel Shams rim — the 'Grand Canyon of Arabia' with 1,000 m drops to the Wadi Ghul below",
    "Trek to the abandoned ghost village of Hadash clinging to the cliff face",
    "Night camp on the canyon rim and watch shooting stars in Oman's unpolluted desert sky",
    "Walk the Balcony Walk — a ledge trail cut into the sheer canyon walls above the gorge",
    "Visit the villages of Al Khateem and explore the traditional falaj irrigation system",
  ],
  "seed-adventure-823": [
    "Pedal the 1,240 km Carretera Austral from Puerto Montt to Villa O'Higgins",
    "Cycle the ferry-crossing section between Hornopirén and Caleta Gonzalo through fjord country",
    "Ride to the Queulat Hanging Glacier where a waterfall drops from the ice sheet",
    "Climb the switchbacks into Cerro Castillo National Park — granite spires above a turquoise lagoon",
    "Wild-camp on the shores of Lago General Carrera — the largest lake in Chile",
    "Navigate the final unpaved gravel section to Villa O'Higgins in Patagonian mud",
    "Take the summer launch across Lago O'Higgins to cross into Argentinian Patagonia",
  ],
  "seed-adventure-824": [
    "Trek from Viswema village through oak and rhododendron forest into the Dzukou Valley",
    "Arrive at the valley floor — a high-altitude meadow carpeted in Dzukou lily and ferns",
    "Camp in the green bowl at 2,452 m with bamboo huts provided by the forest department",
    "Descend via the Jakhama route through Angami Naga villages to Kohima",
  ],
  "seed-adventure-825": [
    "Paddle from Split's Diocletian's Palace waterfront into the Dalmatian archipelago",
    "Land on the island of Brač and walk the Vidova Gora ridge — the highest point in Dalmatia",
    "Kayak the Krka River estuary and snorkel the kelp forests off Šolta",
    "Camp on a pine-covered headland on Hvar island and swim at sunset",
    "Navigate the Paklinski Islands — a chain of uninhabited islands opposite Hvar town",
    "Paddle into the Blue Cave on Biševo — accessible by kayak only in the morning",
    "End in Dubrovnik with a kayak circumnavigation of the old city walls",
  ],
  "seed-adventure-826": [
    "Drive from Islamabad up the Karakoram Highway — the highest paved international road in the world",
    "Cross the Khunjerab Pass at 4,693 m into China and back — a border-crossing road trip",
    "Explore the ancient Silk Road fort of Baltit in Hunza and eat fresh mulberries",
    "Trek above the Passu Cones — cathedral-sharp peaks rising above the Hunza Valley",
    "Visit Sost — the last Pakistani town — for a chai stop before the final climb",
    "Drive the Attabad Lake section — a turquoise reservoir formed by a 2010 landslide",
    "Spend a night in Gilgit with its polo grounds and Buddhist rock carvings",
  ],
  "seed-adventure-827": [
    "Put in at Whitehorse and paddle 740 km down the Yukon River to Dawson City",
    "Shoot the Five Finger Rapids — the only significant whitewater on the lower Yukon",
    "Spot moose wallowing in the willows and black bears fishing at river bends",
    "Camp on gravel bars under the midnight sun — 22 hours of daylight in July",
    "Pass the ghost town of Selkirk and its Hudson's Bay post abandoned in the 1930s",
    "Arrive in Dawson City — a gold rush town on the Klondike junction — after 18 days",
  ],
  "seed-adventure-828": [
    "Join a Bedouin guide at Al-Qusayr and ride camels into the Eastern Desert's Wadi Hammamat",
    "Visit the ancient Mons Claudianus Roman quarry — pink granite cut here for Trajan's Column in Rome",
    "Camp at the base of the Red Sea Mountains under a stellar desert sky",
    "Explore the Coptic monastery of St Paul of Thebes — inhabited since the 4th century",
    "Trek to the Colored Canyon — wind-eroded sandstone walls in ochre, cream and violet",
    "Learn Bedouin navigation by star, wind direction and plant species",
  ],
  "seed-adventure-829": [
    "Walk the Heaphy Track from Brown Hut to Kohaihai — 78 km over five days",
    "Cross the Gouland Downs — an open tussock plateau with nikau palms and kea",
    "Trek through the nikau palm forest on the Kohaihai coast — the southernmost palms in the world",
    "Cross the Heaphy River estuary at low tide to the final hut on the coast",
    "Spot giant wētā and kiwi calls at night near the Heaphy Hut on the coast",
  ],
  "seed-adventure-830": [
    "Acclimatise at Namche Bazaar (3,440 m) and cross the Thame valley to the Renjo La",
    "Climb the Renjo La at 5,340 m with a view down to the turquoise Gokyo Lakes",
    "Descend to Gokyo and summit Gokyo Ri (5,357 m) at dawn for the Everest panorama",
    "Cross the Cho La Pass at 5,420 m on crampons with a direct view of the Nuptse wall",
    "Trek the classic Everest Base Camp route through Lobuche and Gorak Shep",
    "Cross the Kongma La (5,535 m) — the highest of the three passes — on the return",
    "Finish the three-pass circuit at Chhukhung with the Imja Glacier below",
  ],
  "seed-adventure-831": [
    "Drive from Mekele to Erta Ale and walk by night across the black basalt plain to the volcano",
    "Peer into the lava lake of Erta Ale — one of only four permanent lava lakes on Earth",
    "Walk the sulphurous Dallol hydrothermal field — salt pillars, acid pools, and vivid mineral formations",
    "Visit the Afar salt caravan and watch camel trains carrying 40 kg blocks to market",
    "Sleep in a thorn enclosure (zareba) under armed guard in hyena territory",
    "Trek to the edge of the Karum salt lake — 116 m below sea level",
  ],
  "seed-adventure-832": [
    "Kayak the upper Soca River from Trenta — crystal-clear emerald water over white limestone",
    "Run the Grade III rapids at Bovec on a self-guided kayak section",
    "Raft the Soca Gorge below Bovec with canyon walls rising 50 m overhead",
    "Swim in the Kozjak waterfall basin — a 15 m drop into a turquoise pool",
    "Cycle the Vrsic Pass at 1,611 m — the highest mountain pass in Slovenia by bike",
  ],
  "seed-adventure-833": [
    "Fly into Mendoza and acclimatise at Plaza de Mulas base camp at 4,370 m",
    "Carry loads to Camp 1 at Nido de Condores (5,570 m) on the Normal Route",
    "Push to Camp 2 at Cólera (6,000 m) in full expedition gear",
    "Summit day: from Cólera to the summit at 6,961 m via the Canaleta scree gully",
    "Stand on the highest summit in the Americas — the Andes stretching to the Pacific",
    "Descend to base camp in a single day and celebrate with Argentine Malbec",
  ],
  "seed-adventure-834": [
    "Kayak the clear waters of Lake Malawi — Africa's third largest lake — along the Nkhata Bay shoreline",
    "Snorkel the mbuna cichlid fish spectacle at Cape Maclear — hundreds of endemic species",
    "Dive the Illala Gap with reef fish and freshwater sponge formations at 15 m",
    "Trek Livingstonia Escarpment and visit the colonial stone church above the lake",
    "Camp on Mumbo Island — a granite island covered in miombo woodland on the open lake",
  ],
  "seed-adventure-835": [
    "Trek from Phaplu airstrip through Sherpa villages to the Pikey ridge at 4,068 m",
    "Reach the Pikey Peak viewpoint at dawn for an unobstructed panorama of Everest, Lhotse, Makalu and Kanchenjunga",
    "Sleep in authentic Sherpa lodges with minimal tourist traffic",
    "Trek through Junbesi — a Sherpa village with an important Nyingmapa monastery",
    "Descend via Solu Khumbu tea gardens and rice terraces to Salleri",
    "Spot red panda on the forested ridgelines above 3,500 m",
  ],
  "seed-adventure-836": [
    "Hike from Fujisato village into the UNESCO World Heritage Shirakami-Sanchi beech forest",
    "Walk the Anmon Waterfall trail through 130-year-old beech trees to three tiered falls",
    "Spot Japanese serow, black bears and golden eagles on the forest ridge",
    "Traverse the Daikoku-Mori old-growth beech forest — trees up to 200 years old",
    "Sleep in a Matagi hunter lodge in Nishimeya village and taste bear stew",
  ],
  "seed-adventure-837": [
    "Fly by light aircraft into Puerto Maldonado and boat up the Manu River into the biosphere reserve",
    "Walk the oxbow lake trail at Cocha Salvador and spot giant river otters at dawn",
    "Climb the 47 m canopy tower at the research station for a treetop view of Amazonian mammals",
    "Night walk the forest with a spotlight for tapir, armadillo and caimans",
    "Visit the Macaw Lick on the Manu River — hundreds of parrots extracting mineral salts from a clay bank",
    "Track jaguar prints in the riverbank mud with a local Matsigenka tracker",
  ],
  "seed-adventure-838": [
    "Cycle from Batumi on the Black Sea east along the Caucasian foot range to Tbilisi",
    "Climb the Rikoti Pass at 1,000 m through beech and oak forest in central Georgia",
    "Ride through the Alazani Valley wine region — birthplace of wine in the world",
    "Cross the Azerbaijan border at the Lagodekhi Nature Reserve and cycle east",
    "Navigate Baku's chaos and ride the Caspian coastline to Lankaran",
    "Visit a fire temple and the Zoroastrian flame at Yanar Dag near Baku",
  ],
  "seed-adventure-839": [
    "Dive the pristine reefs of Ibo Island — one of Mozambique's most remote dive destinations",
    "Explore the coral gardens of the Quissanga channel at 12 m — untouched, with no other divers",
    "Night dive with bioluminescent plankton off the Medjumbe sand strip",
    "Sail between the Quirimbas islands on a traditional dhow built in the Ibo boatyard",
    "Snorkel the Matemo Island reef with green turtles and hawksbill turtles feeding at low tide",
    "Dive the Ibo wall — a 40 m vertical reef wall with Napoleon wrasse and barracuda schools",
  ],
  "seed-adventure-840": [
    "Fly by bush plane into the Gates of the Arctic — one of the least visited national parks on Earth",
    "Backpack the Alatna River headwaters with no trails, no bridges, no signs",
    "Navigate the Brooks Range on topo map and compass, fording glacial tributaries",
    "Spot a grizzly bear digging Arctic ground squirrels on the open tundra",
    "Walk with the caribou migration — 250,000 animals crossing the valley in July",
    "Camp in a blizzard in August — 9 °C and horizontal snow above 1,500 m",
    "Fly out from Anaktuvuk Pass — an Inupiat village inaccessible by road",
  ],
  "seed-adventure-841": [
    "Begin the Machame Route at Machame Gate (1,800 m) through dense montane rainforest",
    "Climb the Shira Plateau at 3,840 m on day two — an ancient eroded volcano rim",
    "Acclimatise with a day walk to the Lava Tower at 4,600 m, then descend to Barranco",
    "Scale the Barranco Wall — a 300 m scramble with hands and feet required",
    "Approach Kibo crater rim from Barafu camp at 4,673 m for a midnight summit push",
    "Reach Uhuru Peak — Africa's highest summit at 5,895 m — at sunrise",
    "Descend directly to Mweka Gate — a 3,000 m descent in a single afternoon",
  ],
  "seed-adventure-842": [
    "Surf the powerful arctic swells at Unstad Bay — one of the world's northernmost surfable breaks",
    "Bodyboard the Uttakleiv beach break as the Northern Lights dance overhead",
    "Hike Ryten mountain above the Kvalvika beach — a 543 m ridge with a surf photography view",
    "Scramble the Svolværgeita twin peaks — the 'goat horns' of Svolværa above the fishing village",
    "Kayak the Raftsundet Strait between Austvågøya and Hinnøya under the midnight sun",
    "Fish for cod from the wooden dock at Å — the last village at the end of the E10",
  ],
  "seed-adventure-843": [
    "Cycle from Tashkent to Samarkand along the Silk Road highway through cotton fields",
    "Explore the Registan — three 15th-century madrasahs tiled in lapis lazuli and gold",
    "Ride to Shahrisabz — birthplace of Tamerlane — through mountain foothills on quiet roads",
    "Climb the switchbacks to the Takhta Karacha pass (1,778 m) between Samarkand and Shakhrisabz",
    "Visit the Gur-e-Amir mausoleum where Tamerlane's jade sarcophagus rests",
    "Cycle the desert highway to Bukhara — 270 km of flat Kyzylkum landscape",
    "End in Khiva — an intact walled medieval city — and celebrate in the Ichan Kala",
  ],
  "seed-adventure-844": [
    "Board the expedition vessel at Ushuaia and cross the Drake Passage — 900 km of open ocean",
    "Zodiac-land on the Antarctic Peninsula at Portal Point — first step on the continent",
    "Observe Adélie and gentoo penguin colonies at Petermann Island",
    "Push through pack ice into Wilhelmina Bay for a zodiac cruise among humpback whales",
    "Climb the 500 m ridge above Neko Harbour for a panoramic view of the peninsula glaciers",
    "Watch the calving front of the Bryde Glacier from 50 metres in the zodiac",
    "Cross the Antarctic Circle at 66°33′S — a milestone few ships reach on peninsula voyages",
  ],
  "seed-adventure-845": [
    "Trek from Rum Village into the open desert of the Wadi Rum valley with a Bedouin guide",
    "Scramble up Jebel Khazali for inscriptions left by Nabataeans and Thamudic traders",
    "Sleep under a canvas in a Bedouin-run camp with goat milk chai and maqlouba dinner",
    "Navigate the red sand corridors between 700 m sandstone monoliths at dawn",
    "Explore the Lawrence Spring — a rock cleft used by T.E. Lawrence in the Arab Revolt",
    "Walk the Burdah Rock Bridge — a natural arch at 1,700 m requiring a short scramble",
  ],
  "seed-adventure-846": [
    "Paddle sea kayaks from Pangnirtung Fiord into the Auyuittuq National Park fjord",
    "Navigate between icebergs calved from the Penny Ice Cap in Sam Ford Fiord",
    "Camp on the Arctic tundra with narwhal surfacing in the channel at dawn",
    "Kayak beneath the cliffs of Baffin Island's east coast — 1,000 m vertical walls of granite",
    "Spot a polar bear swimming in the open water near the pack ice edge",
    "Fish for Arctic char in the clearwater rivers draining the Penny Highlands",
  ],
  "seed-adventure-847": [
    "Ride Mongolian horses from Kharakhorum — the ancient capital — into the Orkhon Valley",
    "Gallop across open steppe to the Orkhon Waterfall — a 20 m cascade over basalt columns",
    "Overnight in nomadic gers and drink airag and eat tsuivan hand-pulled noodles",
    "Ride to the Erdene Zuu Monastery — built from stones of Genghis Khan's palace",
    "Traverse the Khangai Mountains on horseback at 2,400 m with no roads for 80 km",
    "Visit an eagle hunter family in the Zavkhan aimag and watch a demonstration",
  ],
  "seed-adventure-848": [
    "Acclimatise in Doğubayazıt at 1,625 m below the Persian-style Ishak Pasha Palace",
    "Approach Ararat's base through the Ahora Gorge — the scene of 1840 volcanic eruption",
    "Camp at 3,200 m below the 'Little Ararat' volcanic cone",
    "Summit Ağrı Dağı at 5,137 m — Turkey's highest point and the legendary resting place of Noah's Ark",
    "Descend via the Cehennem Dere valley with views over the Iranian border plain",
  ],
  "seed-adventure-849": [
    "Trek the Drakensberg Traverse from Cathedral Peak to Sani Pass — 230 km of highland plateau",
    "Scramble the Chain Ladder — a 10 m fixed ladder up the sheer basalt wall onto the Lesotho plateau",
    "Camp at 3,000 m on the Lesotho escarpment with 180° views of the lowlands",
    "Cross the Injisuthi Dome summit ridge and descend to the Giant's Castle reserve",
    "Spot the bearded vulture (lammergeier) riding thermals above the Bushmans River Gorge",
    "Hike through the Kamberg area and visit San Bushman rock art caves",
  ],
  "seed-adventure-850": [
    "Boat-hop by bangka from El Nido to the Big Lagoon — limestone karst walls rising from jade water",
    "Kayak into the Small Lagoon through a low limestone arch at low tide",
    "Snorkel the Twin Rocks dive site for jackfish schools and banded sea kraits",
    "Dive the Drop Off at Dilumacad Island — a vertical wall from 5 m to 40 m",
    "Island-hop to Matinloc Shrine and Hidden Beach — accessible only by swimming through a cave",
    "Freedive Shark Point for white-tip reef sharks resting on the sandy bottom",
  ],
  "seed-adventure-851": [
    "Fly by helicopter from Petropavlovsk-Kamchatsky to the Valley of Geysers — 25 km² of active fumaroles",
    "Trek the rim of Mutnovsky Volcano's 2 km active caldera — sulphur vents and boiling mud pools",
    "Climb Avacha Volcano at 2,741 m — an active stratovolcano with lava flows from 1991",
    "Fish for sockeye and king salmon in the Zhupanova River with brown bears fishing 50 m away",
    "Hot spring bathe in Nalychevo Nature Park's thermal pools in the wilderness",
    "Spot Steller's sea eagles and orcas from the Pacific coast cliffs near Khalaktyrsky Beach",
  ],
  "seed-adventure-852": [
    "Drive to the Twyfelfontein rock engravings — over 2,000 San Bushman petroglyphs on sandstone",
    "Walk with a Damara guide and spot desert-adapted black rhino tracks in the gravel riverbed",
    "Track desert elephants to the Huab River — a population unique in tolerating the extreme aridity",
    "Overnight at a fly camp in the Doros Crater with a fire and open sky",
    "Walk the Brandberg White Lady rock art site — a famous Bushman painting in a granite overhang",
    "Spot giraffe, oryx and springbok on the gravel plains at dawn",
  ],
  "seed-adventure-853": [
    "Skin the Lauberhorn and Kleine Scheidegg from Wengen in the blue-shadow morning",
    "Tour through the snow-laden forest above Grindelwald to the Grosse Scheidegg pass",
    "Cross the Lötschenpass at 2,690 m — a historic smugglers' route into the Lötschental",
    "Overnight at the Baltschieder Hut above the Rhône Valley at 2,180 m",
    "Ski the Petersgrat glacier descent to the Kippental in 1,500 m of untracked vertical",
    "End in Kandersteg with a raclette and a look back at the icefields above",
  ],
  "seed-adventure-854": [
    "Enter the Tambopata Reserve by motorised canoe from Puerto Maldonado",
    "Walk the 40 m canopy walkway at the Explorer's Inn and observe macaws above the canopy",
    "Visit the Chuncho macaw clay lick at dawn — hundreds of scarlet, red-and-green and blue-and-yellow macaws",
    "Night walk and spot caiman, giant centipede and kinkajou by headlamp",
    "Fish for arapaima — the world's largest freshwater fish — in the Tambopata oxbow lakes",
    "Track a giant anteater across the Sandoval Lake savanna",
  ],
  "seed-adventure-855": [
    "Fly into Ísafjörður and skin into the Westfjords backcountry above the fjord",
    "Descend the 1,400 m couloirs above Súgandafjörður — deep powder in February",
    "Cross into the Hornstrandir Nature Reserve by ski — no roads, no permanent residents",
    "Camp in an Icelandic mountain hut lit by a whale oil lamp at Hesteyri",
    "Ski the headwall above Aðalvík bay and descend to an abandoned fishing village",
    "Witness the midnight glow of the Westfjords winter sky — neither dark nor light at midday",
  ],
  "seed-adventure-856": [
    "Arrive in Kochi and board a houseboat (kettuvallam) on the Vembanad Lake backwaters",
    "Drift through narrow palm-lined canals watching kingfishers and purple herons",
    "Overnight on the houseboat moored at a village ghat and eat toddy-cooked prawn curry",
    "Trek the Periyar Tiger Reserve on foot with a forest guard — spot bison and wild elephant",
    "Climb Anamudi — South India's highest peak at 2,695 m — through shola grassland",
    "Visit a cardamom and pepper plantation in Munnar and learn spice processing",
    "Kayak through the Kumarakom Bird Sanctuary at dawn watching flocks of painted storks",
  ],
  "seed-adventure-857": [
    "Dive the Drake Bay seamounts — Pacific spotted dolphins and schooling yellowfin tuna",
    "Surf the consistent beach break at Matapalo Point on the tip of Osa Peninsula",
    "Snorkel the Corcovado National Park reefs — one of the most biologically intense places on Earth",
    "Trek the park's interior trail spotting tapir, harpy eagle and four monkey species",
    "Kayak the Río Sirena estuary with bull sharks in the murky lower reaches",
    "Night dive at Caño Island for sleeping whitetip reef sharks on the sandy bottom",
  ],
  "seed-adventure-858": [
    "Begin the Camino Primitivo in Oviedo — the original route used by medieval pilgrims",
    "Cross the Hospitales pass at 1,355 m on a high moorland ridge above the cloud",
    "Descend to Luarca — a white-walled fishing port on the Cantabrian coast — for the night",
    "Trek through the eucalyptus and oak forests of rural Asturias to Grandas de Salime",
    "Join the Camino Francés at Lugo — a Roman walled city — for the final stages",
    "Walk the Rúa do Vilar into Santiago de Compostela and embrace the statue of Santiago",
  ],
  "seed-adventure-859": [
    "Fly to Kulusuk and assemble the sleds and equipment in the Ammassalik fjord",
    "Dog sled across the sea ice of the Sermilik Fjord past iceberg mazes",
    "Ski the Mittivakat Glacier from the inland ice sheet down to the fjord",
    "Stay with East Greenlandic hunters in Tiniteqilaaq — a community of 100 people",
    "Observe the Northern Lights from the dog sled on the open sea ice at −20 °C",
    "Traverse the Isertoq plateau on skis pulling pulks to the glacier edge",
  ],
  "seed-adventure-860": [
    "Start at Alice Springs and follow the Larapinta Trail west along the West MacDonnell ridgeline",
    "Camp at Ellery Creek Big Hole — a permanent waterhole in red quartzite gorge walls",
    "Scramble to the summit of Mount Sonder — the fourth highest summit in the Northern Territory",
    "Walk through Ormiston Gorge and swim in the permanent waterhole at the gorge mouth",
    "Trek the remote western section between Finke Gorge and Redbank Gorge on minimal water carries",
    "Watch the desert sunset at Glen Helen Gorge — the Finke River, one of the world's oldest, flowing below",
  ],
  "seed-adventure-861": [
    "Fly by light aircraft into Nepalgunj and connect to Jumla — the gateway to remote western Nepal",
    "Trek from Jumla through oak and pine forest to the Rara Lake National Park",
    "Reach Rara Lake — Nepal's largest at 3,060 m — a deep blue mirror ringed by pine forests",
    "Camp on the lake shore and watch the Himalayan black bear fishing at dusk",
    "Trek the circuit of the lake through the Mugu and Jumla districts — rarely visited",
    "Return via the Chere Lekh pass and descend to the Tila River valley",
  ],
  "seed-adventure-862": [
    "Trek the Santa Cruz trek from Llamac through the Cordillera Huayhuash high circuit",
    "Camp below the Chopicalqui north face at 5,400 m with Yerupajá in view",
    "Cross the Punta Yanayacu pass at 4,750 m with a 360° view of the Cordillera Blanca peaks",
    "Descend to the Quebrada Quilcayhuanca valley and climb to Laguna Tullpacocha",
    "Visit the Llanganuco Lakes — two linked lagoons of emerald and turquoise below Huascarán",
    "Acclimatise in Huaraz and visit the Chavin de Huantar ruins on the eastern Cordillera slope",
  ],
  "seed-adventure-863": [
    "Launch canoes at Chiawa Camp and paddle downstream on the Zambezi into the wildlife corridor",
    "Drift past elephant herds swimming the river and hippo pods in the shallows",
    "Walk the riverine forest with an armed guide — lion, leopard and buffalo territory",
    "Night paddle and spot crocodile eyes reflecting from the dark river",
    "Camp on a mid-river sand island and fall asleep to the grunts of hippos",
    "Visit the Mana Pools floodplain — famous for elephant standing on hind legs to reach acacia pods",
  ],
  "seed-adventure-864": [
    "Hike the Yushan Main Peak trail from Tatajia trailhead through hemlock and fir forest",
    "Summit Yushan at 3,952 m — Northeast Asia's highest point — at sunrise",
    "Descend to the Dongpu visitor centre and take a bus to Hualien",
    "Cycle the East Rift Valley — 180 km of flat farmland between two mountain ranges",
    "Ride through the Taroko Gorge road — marble canyon walls rising 1,000 m from the river",
    "Cycle the Southern Link Road coastal highway with Pacific Ocean views",
  ],
  "seed-adventure-865": [
    "Fly to Höfn and ski to the Vatnajökull ice cap — the largest glacier in Europe",
    "Navigate the Breiðamerkurjökull outlet glacier on skins in flat light",
    "Camp on the ice sheet at 1,500 m — 10 °C and total silence at midnight",
    "Ski to the Grímsvötn volcanic caldera — an active subglacial volcano",
    "Descend off the western margin of Vatnajökull to the Þórsmörk valley",
    "Witness an ice cave on the glacier's edge before the melt season opens",
  ],
  "seed-adventure-866": [
    "Raft the Brahmaputra from Gelling downstream through Class III rapids in Arunachal Pradesh",
    "Camp on white-sand beaches in the gorge — strictly controlled permit territory",
    "Trek into the Dibang Valley on a side trip — Mishmi hill tribe homeland",
    "Spot the elusive Hoolock gibbon in the riparian forest canopy above the river",
    "Navigate the confluence of the Siang and Lohit rivers at Sadiya",
    "Kayak a section of the tributary Sippi River through the Namdapha National Park buffer",
  ],
  "seed-adventure-867": [
    "Drive into Chobe National Park — home to the highest density of elephants in Africa",
    "Boat safari on the Chobe River past a 100-elephant parade crossing from Botswana to Namibia",
    "Game drive at dawn through the Savuti Marsh for lion hunting on the open plain",
    "Walk with a guide to the Chobe waterfront and observe elephant sparring at the sandy banks",
    "Night drive spotting leopard, brown hyena and aardvark on the Ngwezumba pans",
  ],
  "seed-adventure-868": [
    "Cycle the North Coast 500 from Inverness anti-clockwise through Sutherland and Caithness",
    "Climb the ascent to Bealach na Bà — a 626 m pass with Alpine-style hairpins above Applecross",
    "Pedal the single-track road along the Assynt peninsula past Suilven and Stac Pollaidh",
    "Overnight in a bothy at Sandwood Bay — one of Scotland's most remote beaches",
    "Cycle the Orkney ferry crossing and ride the Ring of Brodgar standing stones at dusk",
    "Ride the Black Isle and Inverness return on the Great Glen Way finish",
  ],
  "seed-adventure-869": [
    "Paddle the Madre de Dios from Puerto Maldonado into the Manu Biosphere Reserve buffer zone",
    "Navigate the river's braided channels and camp on white-sand river beaches",
    "Spot giant river otters at Cocha Cashu oxbow lake — the longest-studied otter population on Earth",
    "Kayak beside groups of river dolphins surfacing in the main channel",
    "Hike up the Atalaya ridgeline for a view over the Amazon headwaters basin",
    "Visit a Shipibo community on the Ucayali tributary and buy painted ayahuasca textiles",
  ],
  "seed-adventure-870": [
    "Walk the Nakasendo from Kiso-Fukushima to Nagiso through the Kiso Valley post towns",
    "Hike between the best-preserved post towns: Magome, Tsumago and Narai",
    "Walk the forested ridge trail between Magome and Tsumago — unchanged since the Edo period",
    "Visit a lacquerware workshop in Narai and watch Edo-era woodworking techniques",
    "Stay in a machiya townhouse minshuku and eat sansai mountain vegetable dinner",
  ],
  "seed-adventure-871": [
    "Enter the Kokoda Track from Owers' Corner and climb immediately into the Owen Stanley Range",
    "Trek the Ghost Mountain switchback to the village of Myola — a WWII supply drop site",
    "Navigate the mud and roots of the Brigade Hill — site of the fiercest 1942 battle",
    "Cross the Eora Creek valley and climb to the Templeton's Crossing memorial",
    "Stay in villages along the trail and learn from Papua New Guinean carriers about the WWII campaign",
    "Descend to Kokoda Station on the northern coast and complete the 96 km track",
  ],
  "seed-adventure-872": [
    "Begin in Dyea, Alaska, and hike the Chilkoot Pass Trail — the 'Golden Staircase'",
    "Scramble the 45° final approach to the 1,067 m Chilkoot Pass on loose scree",
    "Cross into British Columbia and descend to the shores of Bennett Lake",
    "Stay at the restored 1897 tent city of Canyon City — unearthed NWMP post",
    "Board the White Pass & Yukon Route train from Bennett to Skagway at the trail's end",
  ],
  "seed-adventure-873": [
    "Travel by boat along the Irrawaddy from Mandalay to Putao — Myanmar's northernmost town",
    "Trek from Putao into the Hkakabo Razi wilderness on foot through leech forest",
    "Ascend to the base of Hkakabo Razi at 5,881 m — the highest peak in Southeast Asia",
    "Overnight in Tibetan-influenced Rawang villages above 2,000 m",
    "Cross the Langula La pass into the Adung Long valley — unexplored headwaters of the Irrawaddy",
    "Return through the Phongun Razi Wildlife Sanctuary — habitat of red panda and snow leopard",
  ],
  "seed-adventure-874": [
    "Cycle the Cape Peninsula from Cape Town to the Cape of Good Hope along the False Bay coast",
    "Pedal through the vineyard suburbs of Constantia before hitting the mountain road",
    "Bomb the descent from Ou Kaapse Weg over the Silvermine plateau",
    "Reach the Cape of Good Hope — the most south-westerly point of Africa — by bike",
    "Return via Chapman's Peak Drive — a cliffside road dynamited out of the Atlantic face",
  ],
  "seed-adventure-875": [
    "Fly to Longyearbyen in polar night — the sun will not rise for another two months",
    "Skin up the Bjørndalen valley on a still, dark morning and ski down by headlamp",
    "Cross the Adventdalen frozen river and ascend the Adventfjorden north face",
    "See the aurora borealis from the top of the ski run at 600 m — a full arc across the sky",
    "Ski descent through aspen blue twilight at noon — two hours of indirect sunlight daily",
    "Warm up at the Huset bar — the northernmost bar with live music in the world",
  ],
  "seed-adventure-876": [
    "Drive from Uyuni across the Salar de Uyuni — 10,000 km² of white salt crust at 3,656 m",
    "Visit Isla Incahuasi — a coral island rising from the salt flat planted with giant cactus",
    "Photograph the mirror effect at dawn — the thin water layer reflecting sky and volcano",
    "Continue to the coloured Laguna Colorada — a red algae lagoon with 50,000 James's flamingos",
    "Visit Laguna Verde at the base of the 6,025 m Licancabur volcano",
  ],
  "seed-adventure-877": [
    "Board a boat at Gosaba and enter the Sundarbans Tiger Reserve — the world's largest mangrove delta",
    "Night watch from a machaan (watchtower) above the estuary creeks for Bengal tiger movements",
    "Spot irrawaddy dolphins surfacing in the murky tidal channels at low water",
    "Walk the Sajnekhali Wildlife Sanctuary with a forest guard on a tiger-footprint patrol",
    "Watch spotted deer and wild boar on the mudflats at the mangrove edge at dusk",
  ],
  "seed-adventure-878": [
    "Paddle the George Sound route from Te Anau into the remote Fiordland coast",
    "Kayak under the sheer walls of Doubtful Sound — a 40 km fjord with 1,200 m drops to the water",
    "Camp on a rocky platform above the tide line with Fiordland crested penguins nesting nearby",
    "Snorkel the deep water black coral at 10 m — accessible in Fiordland due to the freshwater layer",
    "Paddle into the Dead Sound arm — a perfectly still mirror fjord rarely visited",
    "Spot bottlenose dolphins riding the bow wave of the fjord's only tour boat",
  ],
  "seed-adventure-879": [
    "Cycle the red-earth roads of Viñales Valley between tobacco farms and mogotes",
    "Climb at Viñales Rock — a developed limestone sport crag above the valley floor",
    "Ride through Soroa to the orchid garden — 700 species in a hillside botanical collection",
    "Kayak the Cueva del Indio — a 200 m underground river navigated by boat through cave art",
    "Watch the Mural de la Prehistoria being touched up on the 120 m cliff face of Mogote Dos Hermanas",
  ],
  "seed-adventure-880": [
    "Start at Manali and acclimatise for two days before the high-altitude climb begins",
    "Cross the Rohtang La at 3,978 m — the gateway into Lahaul and the Tibetan rain shadow",
    "Camp at Sarchu (4,290 m) on the high Himalayan plain after 160 km of mountain road",
    "Cycle the Lachulung La at 5,059 m — fifth pass and above the snow line year-round",
    "Navigate the Tanglang La at 5,328 m — one of the highest motorable passes in the world",
    "Freewheel the final 60 km descent into Leh along the Indus River valley",
  ],
};

async function main() {
  const ids = Object.keys(HIGHLIGHTS);
  console.log(`Backfilling highlights for ${ids.length} adventures (batch 1)...`);

  let updated = 0;
  for (const id of ids) {
    const highlights = HIGHLIGHTS[id];
    await prisma.adventure.update({
      where: { id },
      data: { highlights },
    });
    updated++;
    if (updated % 20 === 0) console.log(`  ${updated}/${ids.length}`);
  }

  console.log(`Done — updated ${updated} adventures`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
