import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const HIGHLIGHTS: Record<string, string[]> = {
  "seed-adventure-881": [
    "Fly into Kilimanjaro and drive to Ngorongoro Conservation Area",
    "Descend 600 m into the crater floor — 260 km² of enclosed savanna",
    "Watch a black rhino grazing near the Lerai acacia forest — one of fewer than 30 in the crater",
    "Observe a lion pride hunting wildebeest on the open crater plains at dawn",
    "Spot the flamingo flocks on Lake Magadi — a soda lake in the crater's lowest point",
  ],
  "seed-adventure-882": [
    "Kayak the Verdon River from Castellane through the Grand Canyon du Verdon gorge",
    "Paddle the Class III rapids of the Point Sublime section in the turquoise gorge",
    "Climb the Escalès cliff face — a 300 m limestone sport climbing wall above the river",
    "Abseil from the cliff edge into the gorge and swim back to the kayak",
    "Camp on the Plateau de Valensole — lavender fields visible from the canyon rim above",
  ],
  "seed-adventure-883": [
    "Fly from Bishkek to the base camp at the foot of Khan Tengri (7,010 m) by helicopter",
    "Establish Camp 1 on the Inylchek Glacier at 4,500 m and fix ropes on the north ridge",
    "Climb the marble pyramid's east ridge — sustained 60° ice pitches at 6,000 m",
    "Push to Camp 3 at 6,400 m and acclimatise in a storm for two days",
    "Summit push on a clear window: the top of the Tien Shan at 7,010 m with Kazakhstan and China in view",
    "Rappel the north face and traverse to the South Inylchek base camp by helicopter",
  ],
  "seed-adventure-884": [
    "Drive from Beira into Gorongosa National Park — fully restored after 30 years of civil war",
    "Walk the floodplains at dawn with a tracker spotting elephant, waterbuck and lion",
    "Climb Mount Gorongosa for a view over the Rift Valley and the Cheringoma plateau",
    "Night drive on the Urema floodplain for serval, African civet and aardvark",
    "Canoe the Urema Lake channel to observe hippos and crocodiles at close range",
    "Visit the restoration camp and hear from the scientists rebuilding lion and buffalo populations",
  ],
  "seed-adventure-885": [
    "Trek five days through the Sierra Nevada de Santa Marta jungle from Machete Pelao trailhead",
    "Cross the Buritaca River multiple times on log bridges and wade the deeper sections",
    "Climb to the terraced platforms of Ciudad Perdida at 1,300 m — 650 years older than Machu Picchu",
    "Spend two hours at the citadel before the afternoon return groups arrive",
    "Overnight in hammock camps listening to the jungle and occasional jaguars at night",
  ],
  "seed-adventure-886": [
    "Climb the 5,243 stone steps to Adam's Peak at 2,243 m before dawn for the sunrise pilgrimage",
    "Watch 'the Shadow of the Peak' — Adam's Peak casts a perfect triangular shadow at sunrise",
    "Trek through the Sinharaja Cloud Forest — a UNESCO site of endemic bird species and purple-faced langur",
    "Ride the Ella-Kandy train through tea plantations — one of the world's great train journeys",
    "Cycle the Nuwara Eliya plateau through colonial bungalow estates",
    "Surf the flat-water beginner waves at Weligama Bay on the southern coast",
  ],
  "seed-adventure-887": [
    "Trek from Tafraoute into the granite inselbergs and painted rocks of the Anti-Atlas",
    "Walk the Ameln Valley — a narrow canyon of almond and argan groves between red cliffs",
    "Climb the Tafraout rock — a balancing boulder with panoramic Atlas views",
    "Cross the Jebel Siroua plateau at 3,304 m — the Anti-Atlas's highest summit",
    "Camp with Berber herders at a goat pasture and drink sweet mint tea at a nomad encampment",
    "Visit the Tiznit silver souk and watch Tuareg craftsmen working traditional filigree jewellery",
  ],
  "seed-adventure-888": [
    "Fly to Biratnagar and trek from Taplejung into the Kanchenjunga Conservation Area",
    "Walk the Yalung Glacier approach through Yamphudin — a Sherpa farming village at 2,100 m",
    "Camp on the Yalung Glacier moraine below the south face of Kanchenjunga at 5,143 m",
    "Trek the north side via the Ghunsa Valley for views of the Jannu (Khumbhakarna) north face",
    "Cross the Lapsang La at 5,160 m connecting the north and south circuits",
    "Overnight at a teahouse in Ghunsa village — the highest permanent settlement at 3,400 m",
    "Descend via the Simbua Khola to Taplejung through rhododendron forest",
  ],
  "seed-adventure-889": [
    "Board Canadian canoes at Chitake Springs and paddle downstream into Mana Pools National Park",
    "Drift past elephant herds drinking in the Zambezi shallows in the soft afternoon light",
    "Camp on a mid-river sandbar under a sky filled with Southern Cross and Milky Way",
    "Walk the floodplain on foot with a guide to observe lion and buffalo on the alluvial plain",
    "Spot the rare African wild dog den near the Chikwenga Loop on a morning game walk",
    "Fish for tigerfish in the Zambezi's clear water below the gorge section",
  ],
  "seed-adventure-890": [
    "Swim 3.8 km from the Squamish waterfront across Howe Sound in a wetsuit",
    "Cycle 90 km from Horseshoe Bay to the Whistler bike park on the Sea-to-Sky Highway",
    "Climb the Chief — a 650 m granite dome above Squamish — via the multi-pitch Squamish Buttress",
    "Kayak the Shannon Falls marine corridor and spot harbour seals on the kelp beds",
  ],
  "seed-adventure-891": [
    "Dive the Batu Bolong seamount off Komodo Island — manta rays, turtles and grey reef sharks",
    "Hike the Komodo Island trail at dawn to see Komodo dragons ambushing deer on the savanna",
    "Snorkel the Pink Beach — named for its pink coral-fragment sand — with reef sharks below",
    "Dive the Crystal Rock pinnacle for schooling bumphead parrotfish and rainbow runners",
    "Trek Rinca Island's ridgeline for panoramic views of the Komodo archipelago",
    "Dive the Tatawa Besar channel in the current surge for eagle rays and Napoleon wrasse",
  ],
  "seed-adventure-892": [
    "Skin from the Pradollano ski resort and climb above the pistes into the Sierra Nevada backcountry",
    "Ascend Veleta at 3,394 m — the southernmost ski touring peak in continental Europe",
    "Ski the long Refugio Poqueira approach from the Mulhacén north face in spring corn",
    "Traverse the high ridge between Alcazaba and Mulhacén — Iberia's highest point at 3,479 m",
    "Descend the south face on spring snow with a view of the Mediterranean coast and Morocco",
    "Overnight at the Refugio Poqueira at 2,500 m with tapas and Sierra Nevada red wine",
  ],
  "seed-adventure-893": [
    "Rent a motorbike in Ha Giang town and ride north toward the Dong Van Karst Plateau",
    "Navigate the Ma Pi Leng Pass — a 2,000 m cliff road dropping vertically to the Nho Que River",
    "Stay overnight in an H'mong or Dao hill tribe village guesthouse",
    "Visit Dong Van Sunday market — minority peoples in full traditional dress selling herbs and livestock",
    "Ride through the gate of the Lung Cu flagpole — the northernmost point of Vietnam",
    "Descend to Meo Vac and ride the full pass in reverse for sunset light on the karst",
  ],
  "seed-adventure-894": [
    "Fly to Addis Ababa and drive to Robe — the base for the Bale Mountains",
    "Trek the Sanetti Plateau at 4,377 m — the largest afroalpine habitat in Africa",
    "Track the Ethiopian wolf — the rarest canid in the world — hunting giant mole rats at dawn",
    "Walk the Harenna Forest — Africa's second largest cloud forest — below the plateau",
    "Spot mountain nyala, Bale monkey and African wild dog in the plateau moorland",
    "Night walk the Dinsho plains for spotted hyena and serval",
    "Visit the Dinsho Wildlife Centre and learn about Ethiopian wolf conservation",
  ],
  "seed-adventure-895": [
    "Fly to Pico Island and hike the Pico Mountain — Portugal's highest peak at 2,351 m — via the crater trail",
    "Kayak the lava coastline of Faial Island between black volcanic sea stacks",
    "Dive the Princess Alice Bank — blue and mako sharks in open Atlantic water",
    "Trek the Flores Island calderas — seven crater lakes in different colours",
    "Swim in the natural lava pools at Biscoitos — protected from Atlantic swell by centuries-old stone walls",
    "Whale-watch from Faial for sperm whales in the deep Atlantic channel",
  ],
  "seed-adventure-896": [
    "Cycle from Santa Maria to Abra Malaga at 4,316 m — a 3,600 m altitude gain in a single morning",
    "White-water raft the Urubamba River from Santa Teresa through Class III-IV rapids",
    "Hike the Santa Teresa Valley route — the 'backdoor' Inca Jungle Trail to Aguas Calientes",
    "Zip-line above the cloud forest canopy on the descent toward the Urubamba",
    "Arrive at Machu Picchu at sunrise on the final day — the citadel emerging from the clouds",
  ],
  "seed-adventure-897": [
    "Walk Alta Via 2 from Bressanone (Brixen) south to Feltre — 180 km through the eastern Dolomites",
    "Cross the Plose plateau and descend into the Puez-Odle nature reserve",
    "Traverse the Pale di San Martino — a 50 km² plateau of white dolomite at 2,400 m",
    "Scramble to the summit of Cima Vezzana at 3,192 m on a guided day loop",
    "Overnight at the Rifugio Passo Rolle below the Sass Maor south wall",
    "Descend through the Primiero Valley with the Dolomiti Bellunesi visible ahead",
  ],
  "seed-adventure-898": [
    "Trek the Ozegahara boardwalk — Japan's largest high-altitude wetland above Nikko",
    "Camp at the Hatomachi Pass hut below the Aizu-Koma ridge at 1,700 m",
    "Summit Shibutsu-san at 2,228 m — the ancient peak above the Oze marshland",
    "Walk the Nikko Suginamiki — a 35 km cryptomeria avenue planted in 1625 along the pilgrimage road",
    "Soak in the Yumoto onsen at the edge of the Nikko National Park",
  ],
  "seed-adventure-899": [
    "Drive to Sossusvlei at dawn and climb Dune 45 for a view of the sand sea at first light",
    "Walk Dead Vlei — a white clay pan surrounded by the world's tallest sand dunes and 900-year-old dead camelthorn trees",
    "Hike the Sesriem Canyon — a 30 m deep gorge carved by the Tsauchab River into the desert floor",
    "Drive east into the Kalahari and walk with a !Kung San tracker reading spoor in the red sand",
    "Night drive the Kalahari and spot aardwolf, springhare and brown hyena",
    "Overnight at a Kalahari bush camp with the Milky Way visible horizon to horizon",
    "Visit the Quiver Tree Forest — a stand of 300-year-old aloe dichotoma in the rocky Kalahari",
  ],
  "seed-adventure-900": [
    "Fly to Skardu and drive to Askole — the last village before the Karakoram wilderness begins",
    "Trek the Baltoro Glacier — 60 km of ice highway through the greatest concentration of 8,000 m peaks",
    "Camp at Concordia — the 'Throne Room of the Mountain Gods' — surrounded by K2, Broad Peak and the Gasherbrums",
    "Stand at K2 Base Camp at 5,000 m and look up at the world's second highest mountain",
    "Trek to the Gondogoro La (5,585 m) if conditions allow — a challenging crossing back to Hushe",
    "Walk past the Trango Towers — the world's largest nearly vertical cliff faces",
    "Return via Urdukas and the Biange campsite through the most spectacular alpine scenery on Earth",
  ],
  "seed-adventure-901": [
    "Drive from Reykjavik to Skaftá under the cloud-covered Vatnajökull ice cap",
    "Ride snowmobiles across the Mýrdalsjökull glacier at night searching for the aurora",
    "Watch the Northern Lights break overhead while stationary on the ice sheet at 1,000 m",
    "Visit the Skaftá eruption site — still steaming from the 2023 volcanic activity",
    "Return via the South Coast ice lagoon at Jökulsárlón for floating iceberg photography",
  ],
  "seed-adventure-902": [
    "Walk from Maras village to the Salineras — thousands of salt evaporation pools carved into the hillside",
    "Hike the ancient agricultural circles of Moray — Inca terracing creating microclimates 30 °C apart",
    "Trek the ridgeline above Pisac and descend through the Inca trail checkpoints",
    "Visit the Chinchero textile market and watch the cochineal dyeing and backstrap loom weaving",
  ],
  "seed-adventure-903": [
    "Canoe the Oulanka River from Juuma rapids through Grade I and II white water",
    "Trek the Karhunkierros (Bear's Ring) — Finland's most famous trail through ancient river canyon",
    "Swim in the canyon's Myllykoski rapids — icy clear water over polished red granite",
    "Walk the suspension bridges over the gorge at Jyrävä — Finland's most powerful waterfall",
    "Camp above the tree line at Valtavaara fell and spot the Siberian jay",
    "Overnight in the Oulanka visitor centre log cabin and eat smoked salmon soup",
  ],
  "seed-adventure-904": [
    "Fly to Kathmandu and trek from Syabru Besi into the Langtang Valley",
    "Pass through Lama Hotel at 2,480 m and climb to Langtang village — destroyed in the 2015 earthquake",
    "Camp at Kyanjin Gompa at 3,870 m below Langtang Lirung (7,227 m)",
    "Climb Tsergo Ri at 4,984 m for a view over the Tibetan border and the Langtang massif",
    "Walk the moraine to the Langtang Glacier tongue and eat yak butter tea at the cheese factory",
    "Descend via the Ghode Tabela yak pastures and overnight in a typical Tamang guesthouse",
  ],
  "seed-adventure-905": [
    "Drive from Marrakech to the Imlil trailhead at 1,740 m in the High Atlas",
    "Acclimatise at the Refuge du Toubkal at 3,207 m and summit Toubkal at 4,167 m in winter",
    "Crampons on from the Neltner Hut — the final push is 60° snow on the South Cwm",
    "Stand on the summit of North Africa's highest peak in full winter silence",
    "Descend to Imlil through Berber villages and drink sweet mint tea at Aroumd",
  ],
  "seed-adventure-906": [
    "Fly to Fernando de Noronha — a volcanic archipelago 350 km off the Brazilian coast",
    "Dive the Sueste Bay for spinner dolphins, sea turtles and reef sharks at 15 m",
    "Snorkel the Atalaia natural pools — rockpools accessible only on the low-tide guided walk",
    "Night dive the Cabeço do Frade for sleeping nurse sharks and scorpionfish",
    "Hike Pico Alto at 323 m for a panoramic view of all 21 islands of the archipelago",
    "Dive the Buraco das Cabras — a basalt lava tube at 30 m with moray eels and lobsters",
    "Watch spinner dolphins riding the port side waves at Baía dos Golfinhos at dawn",
  ],
  "seed-adventure-907": [
    "Trek from Gangotri (3,048 m) through the valley of the sacred Bhagirathi River",
    "Walk the Chirbasa and Bhojbasa meadows with Shivling and Bhagirathi peaks above",
    "Reach Gomukh (4,023 m) — the snout of the Gangotri Glacier where the Ganges rises",
    "Cross the glacier and climb to the Tapovan meadow at 4,463 m for views of Shivling's north face",
    "Overnight at the Nandanvan base camp below Bhagirathi I (6,856 m)",
    "Return via the Kedartal Lake route — a 4,750 m high-altitude tarn below Thalay Sagar",
  ],
  "seed-adventure-908": [
    "Ski 42 km from Maloja to S-chanf on a classic Nordic marathon course",
    "Glide through the frozen Engadin valley on 3 cm of fresh morning groomed track",
    "Pass the frozen Lake Sils and Lake Silvaplana — the course's most spectacular sections",
    "Climb the 1 km long gentle ascent of the Punt Muragl and ski through St Moritz village",
    "Finish at the Engadin valley floor below the Bernina Alps with 13,000 other participants",
  ],
  "seed-adventure-909": [
    "Drive south from Nairobi and enter Amboseli at the Meshanani gate",
    "Game drive the Enkongo Narok Swamp for elephant herds — often 200+ animals feeding in the reeds",
    "Walk with a Maasai guide on the open Amboseli plains as Kilimanjaro clears of cloud",
    "Watch a cheetah family hunting Thomson's gazelle on the open short-grass plain",
    "Night at a tented camp with giraffe and zebra grazing under Kilimanjaro",
    "Visit a Maasai village and witness the jumping ceremony (adumu) and enkiama fire-making",
  ],
  "seed-adventure-910": [
    "Fly to Oslo and drive to Otta — the gateway to the Rondane plateau",
    "Ski the classic Peer Gynt trail through Vinstra to Lillehammer — 220 km of marked tracks",
    "Cross the Rondane and Jotunheimen mountain plateaus on 4-day hut-to-hut ski stage",
    "Navigate by map across the open plateau in poor visibility — whiteout navigation drill",
    "Ski the descent to Mysusæter hut through old-growth birch forest in knee-deep powder",
    "Warm up with rømmegrøt sour cream porridge and elk stew at each hut along the way",
  ],
  "seed-adventure-911": [
    "Fly into Maroantsetra and take a boat to the Masoala Peninsula tip",
    "Trek the Masoala rainforest — one of the last intact lowland rainforests in Madagascar",
    "Snorkel the Tampolo Marine Park — pristine coral reef with hundreds of endemic fish species",
    "Night walk and spot chameleons, leaf-tailed geckos and mouse lemurs by headlamp",
    "Hike to the Camp Rombo ridgeline for a view over the Bay of Antongil",
    "Spot the red-ruffed lemur and aye-aye in a community managed forest",
    "Kayak the Masoala coast through sea caves and around granite sea stacks",
  ],
  "seed-adventure-912": [
    "Run the Midnight Sun Marathon on the longest day — 22 km around Reykjavik at midnight",
    "Cycle the Ring Road from Reykjavik clockwise through the Westfjords section",
    "Ride the F-roads on a gravel bike through the Landmannalaugar lava fields",
    "Camp by the Myvatn geothermal lake and watch steam rising from the lava field",
    "Cycle the North Iceland coast from Akureyri through the whale-watching capital of Húsavík",
    "Climb Snæfellsjökull glacier — the setting of Verne's Journey to the Centre of the Earth",
  ],
  "seed-adventure-913": [
    "Surf Cloud 9 — a world-class right-hand reef break over shallow coral off Siargao's General Luna",
    "Paddle out in the dawn glass with a peak entirely to yourself before the crowds arrive",
    "Island-hop by bangka to Naked Island, Daku Island and Guyam Island for snorkelling and swimming",
    "Trek the interior jungle to the Sugba Lagoon — a jade-green mangrove-lined cove",
    "Freedive the Sohoton Cove sea caves at low tide, swimming through bioluminescent jellyfish pools",
    "Learn to navigate the Cloud 9 barrel from a local Siargao surf guide",
    "Overnight in a bamboo surf camp on the beach with hammock and fresh coconuts",
  ],
  "seed-adventure-914": [
    "Skin up the Back Bowl of Lake Louise above the piste and drop into the Temple Lodge backcountry",
    "Ski the classic Skoki Valley tour — 28 km through the Front Ranges to Skoki Lodge",
    "Climb Mount Richardson at 3,086 m and ski the long NE couloir back to the valley",
    "Traverse to the Boulder Pass and ski down to Hidden Lake in untracked powder",
    "Overnight at Skoki Lodge — a historic 1930s log cabin hut in the wilderness",
    "Ski the final descent back to Lake Louise Village on the morning groomed corduroy",
  ],
  "seed-adventure-915": [
    "Fly to Lalibela and walk the rock-hewn churches — 11 monolithic churches carved below ground level",
    "Descend into Bete Giyorgis (Church of St George) — a cross-shaped monolith cut 13 m into the rock",
    "Trek the Lalibela to Simien Mountains trail through Wollo highlands of Tigrinya farmers",
    "Cross the Wolkefit Pass at 2,800 m and descend into the Bashilo River gorge",
    "Trek through Meket and Gashena market towns on hand-cut mule trails",
    "Arrive at the Simien escarpment and spot gelada baboons on the cliff edges above the gorge",
  ],
  "seed-adventure-916": [
    "Begin the Overland Track at Ronny Creek in Cradle Mountain-Lake St Clair National Park",
    "Summit Cradle Mountain at 1,545 m on day one with views across the glacial plateau",
    "Walk the Waterfall Valley Hut on the moorland plateau — carnivorous sundew and Tasmanian devils",
    "Scramble to the top of Mount Ossa — Tasmania's highest peak at 1,617 m — on a day loop",
    "Cross the Narcissus River by ferry on Lake St Clair and arrive at Cynthia Bay",
    "Spot the rare orange-bellied parrot on the button grass plains near Pelion Hut",
  ],
  "seed-adventure-917": [
    "Fly to Lukla and trek to Namche Bazaar for a two-night acclimatisation rest",
    "Walk to the Everest View Hotel at 3,880 m for the classic Ama Dablam and Everest panorama",
    "Trek to Tengboche Monastery — a 3,867 m gompa below the Ama Dablam south face",
    "Hike the Gokyo Lakes as a side loop and summit Gokyo Ri for the Everest horizon",
    "Return to Namche and descend to Phakding through the deep Dudh Kosi gorge",
  ],
  "seed-adventure-918": [
    "Start in Malaga and cycle east up the Axarquía coast through avocado and subtropical fruit farms",
    "Climb the Puerto del León — a 15 km ascent through cork-oak forest to 1,100 m",
    "Descend into the Guadalhorce River valley and ride to Antequera's Dolmen site",
    "Climb the Puerto de las Pedrizas and push into the Sierra Nevada foothills above Granada",
    "Reach the Pradollano ski resort at 2,100 m — finish line with Alhambra below in the valley",
  ],
  "seed-adventure-919": [
    "Fly to Bali and take the ferry to Flores for a motorbike pickup in Labuan Bajo",
    "Ride the Trans-Flores Highway east from Labuan Bajo through volcanic highlands",
    "Hike the three-coloured crater lakes of Kelimutu — each lake a different colour due to mineral composition",
    "Visit the traditional weavers of Wolotopo village making ikat textiles on backstrap looms",
    "Ride the Bajawa highlands through Ngada villages with megalithic ancestor shrines",
    "Snorkel the Riung 17 Islands Marine Park on the north coast",
    "End in Maumere and catch a flight back to Bali from the east Flores coast",
  ],
  "seed-adventure-920": [
    "Fly to Ilulissat and assemble dog sleds and equipment on the sea ice of Disko Bay",
    "Mush across the Icefjord — UNESCO World Heritage — beside the world's most productive glacier",
    "Camp on the sea ice with the Sermeq Kujalleq glacier calving in the background",
    "Watch polar bear tracks intersect the sled trail overnight on the frozen bay",
    "Drive the dogs to the iceberg graveyard — where Disko Bay's icebergs finally ground and stop",
    "Experience the ice blink — a white light on the horizon reflected from the glacier 30 km away",
  ],
  "seed-adventure-921": [
    "Trek from Tinqui village and cross the pampa below the Ausangate massif at 4,700 m",
    "Reach the hot springs of Pacchanta and soak in the thermal pools below the glacier",
    "Climb to the Rainbow Mountain viewpoint above Vinicunca at 5,100 m",
    "Walk the Ausangate circuit with a Quechua arrieros (mule drivers) carrying gear",
    "Camp in the shadow of the Ausangate glacier at 5,000 m and watch alpaca herds return at dusk",
  ],
  "seed-adventure-922": [
    "Arrive in Hikkaduwa and rent a surfboard — consistent 1–2 m left-handers peel along the reef",
    "Surf Arugam Bay's Main Point — a long right-hander considered Sri Lanka's best wave",
    "Hire a local guide for Pottuvil Point — a rarely-surfed rivermouth with 200 m rides",
    "Explore the Bundala National Park flamingo lagoons by bicycle between surf sessions",
    "Eat a fish curry at a fisherman's beach shack on Ahangama's reef-break coast",
    "Learn to surf from a local instructor on the beginner beach break at Weligama",
    "Spot sea turtles nesting on Rekawa Beach at dusk during a guided turtle watch",
  ],
  "seed-adventure-923": [
    "Skin from the Gudauri ski area into the Truso Valley backcountry above the military highway",
    "Ski the deep gullies of the Khada Gorge couloirs — north-facing powder in January",
    "Camp at the Kazbegi backcountry hut below the Gergeti Glacier at 2,700 m",
    "Ski the Keli Plateau — an open high plateau at 3,100 m with no piste markers for 25 km",
    "Tour to the Arkhoti Valley and ski tree runs through old-growth Caucasian fir forest",
    "Overnight in Stepantsminda village guesthouse with Georgian khachapuri and chacha brandy",
  ],
  "seed-adventure-924": [
    "Fly to Port Blair and take the ferry to Havelock Island",
    "Dive the Lighthouse at Havelock — a 22 m coral pinnacle with Napoleon wrasse and barracuda",
    "Snorkel Elephant Beach — a remote cove accessible only by boat with crystal visibility",
    "Dive the Barracuda City site at Neil Island for massive schools of chevron barracuda",
    "Trek the forest interior of South Andaman Island to spot the Andaman crake and serpent eagle",
    "Night dive the Mahatma Gandhi Marine National Park for sea horses and decorator crabs",
    "Kayak through the mangroves of Baratang Island to the mud volcano and limestone caves",
  ],
  "seed-adventure-925": [
    "Take a jeep from La Paz up to the Yungas Road starting point at La Cumbre Pass at 4,700 m",
    "Descend 64 km and 3,500 m of vertical on a mountain bike through cloud forest to Coroico",
    "Navigate the hairpin bends where the road is carved into a sheer 600 m cliff face",
    "Ride through waterfalls cascading onto the road on the mid-descent section",
    "Arrive in Coroico at 1,700 m in the humid yungas lowlands and celebrate",
  ],
  "seed-adventure-926": [
    "Walk the Maasai Mara Conservancy with an armed Maasai guide on foot",
    "Track lion and leopard on foot through the Olarro and Lemek conservancies",
    "Watch the Mara River crossing of the Great Migration — thousands of wildebeest braving crocodiles",
    "Walk the full length of a cheetah family's hunting range in a single morning",
    "Overnight at a mobile fly camp on the open Mara plains — no fence, just firelight",
    "Visit a Maasai inkiama (village meeting) and learn the history of the Mara conservancy model",
    "Explore the Mara Triangle on a pre-dawn walking safari under the Southern Cross",
  ],
  "seed-adventure-927": [
    "Begin at Whakapapa Village and hike to Ketetahi Hut via the volcanic terrain of Ngauruhoe",
    "Cross the Tongariro Alpine Crossing — one of the world's great one-day walks",
    "Hike through the South Crater and clamber the volcanic rock to the Red Crater rim at 1,886 m",
    "Descend to the Emerald Lakes — three vivid mineral lakes in the crater",
    "Circuit to the Blue Lake — a sacred Maori tapu lake not to be entered",
    "Descend to Waihohonu Hut through tussock grassland with Ruapehu visible to the south",
  ],
  "seed-adventure-928": [
    "Ride from Neiva into the Tatacoa Desert — a 330 km² red clay and grey cactus badlands",
    "Cycle the labyrinthine clay canyons of the Cuzco sector — Mars-red gullies with no shade",
    "Photograph the fossils of mastodon and giant turtle exposed by erosion in the canyon walls",
    "Camp at the Tatacoa Astronomical Observatory for a night of southern-sky stargazing",
    "Ride to the Ocre sector — yellow-ochre eroded columns below a volcanic escarpment",
  ],
  "seed-adventure-929": [
    "Start the Arctic Circle Trail at Kangerlussuaq — 165 km of unmarked Arctic tundra to Sisimiut",
    "Cross the Russell Glacier outwash plain and climb onto the West Greenland plateau",
    "Navigate by GPS across the featureless tundra — no blazes, no footbridges on most rivers",
    "Camp beside Lake Amitsorsuaq — a vast Arctic lake with caribou on the far shore",
    "Spot white Arctic fox hunting lemmings on the open tundra above the treeline",
    "Descend to the sea at Sisimiut — Greenland's second largest town — and eat at the only restaurant",
  ],
  "seed-adventure-930": [
    "Take the cable car from Sa Pa to the Fansipan summit station at 3,143 m",
    "Trek the Fansipan traditional route from Tram Ton Pass — a 2-day technical climb",
    "Navigate the bamboo and cloud forest above 2,200 m on the ridge approach",
    "Summit Fansipan at 3,143 m — the highest peak in Indochina — at dawn",
    "Descend via the traditional route and overnight at a mountain camp",
  ],
  "seed-adventure-931": [
    "Fly to Nanyuki and approach Mount Kenya via the Sirimon Gate at 2,650 m",
    "Trek through the Mackinder Valley — giant groundsel and lobelia in the Afroalpine zone",
    "Camp at Shipton's Camp at 4,236 m below the north face of Batian and Nelion",
    "Climb the technical Batian summit at 5,199 m via the Normal Route with ice axe and crampon",
    "Descend via the Chogoria route through heather moorland and the Hall Tarns",
    "Soak in the Rutundu log cabin on Lake Alice at 3,200 m on the return day",
  ],
  "seed-adventure-932": [
    "Fly to Calama and drive to San Pedro de Atacama — the driest town in the driest desert on Earth",
    "Trek the Valle de la Luna at sunset — salt and gypsum formations glowing orange and pink",
    "Climb the Licancabur Volcano approach trail to 5,000 m above the Bolivian border",
    "Stargazing at ALMA Observatory — the highest astronomical site in the world at 5,100 m",
    "Trek to the Piedras Rojas — red volcanic rocks above a white salt lake at 4,200 m",
    "Walk El Tatio Geyser field at sunrise — a 60-geyser field active only in the morning cold",
  ],
  "seed-adventure-933": [
    "Cycle from Mandalay to Pindaya through the Shan plateau on Myanmar's finest back roads",
    "Visit the Pindaya Caves — 8,000 Buddha images in a limestone cavern above the Sone lake",
    "Ride the lakeside road to Nyaungshwe and board a traditional longtail for the Inle approach",
    "Cycle through the floating garden islands of Inle Lake on raised embankment paths",
    "Cross from Inle to the Indein ruins by pedal boat through lily pads and reed marshes",
  ],
  "seed-adventure-934": [
    "Start at the Maligne Lake trailhead and hike into the Skyline Trail wilderness",
    "Trek the Shovel Pass at 2,560 m with a 360° view of the Colin Range and Maligne Valley",
    "Camp at the Curator Lake campsite — a glacial tarn below the Notch ridge",
    "Descend via the Signal Mountain trail through sub-alpine fir and meadow to Jasper town",
    "Spot grizzly bears and mountain caribou on the alpine tundra sections",
  ],
  "seed-adventure-935": [
    "Drive from Dushanbe over the Anzob Pass at 3,372 m and descend to the Nurek reservoir",
    "Navigate the Pamir Highway east from Khorog — the world's second highest road",
    "Drive the Wakhan Corridor — the 'Narrow Land' sandwiched between Afghanistan and China",
    "Camp at the Alichur plateau with the Eastern Pamirs at 4,200 m of flat, windswept desert",
    "Visit the Karakul Lake — a 3,914 m meteorite crater lake on the Roof of the World",
    "Cross the Ak-Baital Pass at 4,655 m — the highest point on the Pamir Highway",
    "End in Osh, Kyrgyzstan, having traversed 1,200 km of the world's most remote road",
  ],
  "seed-adventure-936": [
    "Cycle south from Swakopmund along the Atlantic coast toward the Skeleton Coast Park",
    "Ride across the gravel plains past seal colonies at Cape Cross — 250,000 Cape fur seals",
    "Navigate the dune crossings at Hoanib Rivermouth on fat tyres in deep sand",
    "Overnight at a remote bush camp on the Ugab River dry riverbed",
    "Cycle through the fog belt and watch fog-drinking beetles collecting moisture on their backs",
    "Reach the Kunene River mouth at the Angolan border — the northernmost point of the park",
  ],
  "seed-adventure-937": [
    "Trek from Mollepata village through Soraypampa meadows toward the Salkantay glacier",
    "Camp at Soraypampa at 3,900 m below the unclimbed south face of Salkantay (6,271 m)",
    "Cross the Salkantay Pass at 4,638 m on day two with a direct view of the ice pyramid summit",
    "Descend through cloud forest and orchid zones to Santa Teresa at 1,500 m",
    "Hike the final approach along the Inca trail river valley to Aguas Calientes",
    "Enter Machu Picchu via the Sun Gate (Inti Punku) at dawn on the final day",
  ],
  "seed-adventure-938": [
    "Fly to Dar es Salaam and drive to Iringa — the gateway to Ruaha National Park",
    "Walk game with an armed scout on the Great Ruaha River floodplain",
    "Watch a pack of African wild dogs denning near the Mwagusi Camp in the dry season",
    "Track the park's 10,000 elephant on a foot patrol through the baobab woodland",
    "Game drive at dawn on the Usangu Flats for the highest density of ground hornbill in Tanzania",
    "Night safari on the river bank for leopard and lion hunting the kongoni herds",
  ],
  "seed-adventure-939": [
    "Paddle from Seward into Resurrection Bay — where blue icebergs calve from the Harding Icefield",
    "Sea kayak beneath the tidewater glaciers of Northwestern Fjord in Kenai Fjords",
    "Watch a humpback whale bubble-net feeding at the mouth of Aialik Bay",
    "Observe a Steller sea lion colony hauled out on the sea stacks of Three Hole Point",
    "Camp on a cobble beach with horned puffins and black-legged kittiwakes nesting above",
    "Paddle the protected waters of Bear Glacier Lagoon — an iceberg-filled lake at the glacier snout",
  ],
  "seed-adventure-940": [
    "Run the Tour du Mont Blanc ultra circuit — 170 km around the massif through three countries",
    "Cross into Italy at the Grand Col Ferret at 2,537 m with Grandes Jorasses in view",
    "Descend to Courmayeur and climb the ridge above Aosta Valley on the east flank",
    "Cross into Switzerland at the Col de la Seigne above Chamonix's Italian neighbours",
    "Summit the Tête Nord des Fours at 2,756 m for the panorama of the full Mont Blanc chain",
    "Finish in Chamonix and eat a raclette below the Aiguille du Midi",
  ],
  "seed-adventure-941": [
    "Board a 5th-station bus at Kawaguchiko at midnight for the dawn summit attempt",
    "Climb the Yoshida Trail from 2,305 m through crowds of pilgrims in headlamp procession",
    "Pass the Eighth Station teahouses at 3,400 m with a hot miso soup stop",
    "Reach the crater rim at 3,776 m just as the sun clears the Pacific horizon",
    "Walk the O-Hachi-Meguri — the 3 km circuit around the crater rim above the clouds",
  ],
  "seed-adventure-942": [
    "Drive from Reykjavik to Landmannalaugar — where the volcanic highlands begin",
    "Hike the Brennisteinsalda volcano — its slopes streaked in sulphur yellow and rust red",
    "Swim in the natural hot spring pool where a thermal river meets a cold waterfall",
    "Walk the obsidian lava field of Laugahraun — formed in 1477 and still sharp underfoot",
    "Camp at Landmannalaugar and join the Laugavegur Trail south to Þórsmörk",
  ],
  "seed-adventure-943": [
    "Trek from the Nyakalengija trailhead in Kibale Forest through the bamboo zone to the Rwenzori snowfields",
    "Camp at the Elena Hut at 4,541 m below Margherita Peak — the highest summit on the range",
    "Climb the Stanley Glacier and navigate the exposed ridge to Margherita at 5,109 m",
    "Stand on one of the most remote ice-capped summits in Africa — equatorial glaciers melting yearly",
    "Descend through the Bigo Bog — a bizarre moorland of giant lobelia and heather at 3,500 m",
    "Trek the Kitandara Lakes campsite below the glaciated cirque of the Scott-Elliot Pass",
  ],
  "seed-adventure-944": [
    "Fly to Jomsom and walk north across the Mustang border check on a restricted permit",
    "Trek through the ochre and white clay canyon villages of Chele and Samar",
    "Enter Lo Manthang — the 15th-century walled capital of the Kingdom of Mustang",
    "Visit the Thugchen Gompa monastery with its 500-year-old murals and giant gilt Maitreya statue",
    "Trek to the sky cave burial sites at Jhong — ancient cliff-face burial chambers above the village",
    "Explore the Chosar valley with its ancient fortresses and cave hermitages on red cliffs",
    "Return via the Kali Gandaki gorge — the world's deepest valley at 5,571 m deep",
  ],
  "seed-adventure-945": [
    "Fly from Cape Town to Punta Arenas and then by Twin Otter to the Antarctic interior",
    "Ski-kite the first 300 km from Hercules Inlet toward the South Pole",
    "Navigate the polar plateau on compass and GPS — no landmarks for 1,000 km",
    "Cross the Thiel Mountains — the only geological feature visible above the ice for 500 km",
    "Ski 55 days across the Antarctic interior pulling a 100 kg pulk",
    "Arrive at the Amundsen-Scott South Pole Station and stand at 90°S",
    "Fly back to Punta Arenas by Twin Otter from the geographical South Pole",
  ],
  "seed-adventure-946": [
    "Fly to Ushuaia — the southernmost city in the world — and enter Tierra del Fuego National Park",
    "Hike the Coastal Trail along the Beagle Channel with Andean condors riding thermals above",
    "Trek to Laguna Esmeralda through lenga beech forest with guanaco herds on the hillsides",
    "Walk the Cerro Alarken ridge for views of the Chilean archipelago and the Cape Horn islands",
    "Boat the Beagle Channel to Isla Navarino and hike the Dientes Circuit on the southernmost trek",
  ],
  "seed-adventure-947": [
    "Fly to Kuala Lumpur and take a bus to Taman Negara's Kuala Tahan entry point",
    "Night walk the world's longest canopy walkway at 45 m above the forest floor",
    "Trek the 9-day Tahan Trail to the summit of Gunung Tahan — Peninsular Malaysia's highest peak at 2,187 m",
    "Navigate the Teku River valley by raft and ford the Sungai Tahan eight times",
    "Spot Malayan tiger tracks in the riverside mud and spot elephants at the Belau saltlick",
    "Overnight in an Orang Asli village and learn the blow-pipe hunting technique",
    "Return by boat down the Tembeling River and spot river otters and kingfishers",
  ],
  "seed-adventure-948": [
    "Trek from Huancacalle village past the Inca ruin of Vitcos — Manco Inca's last capital",
    "Follow the remote jungle trail to Espiritu Pampa — the true last capital, overgrown with cloud forest",
    "Cross three mountain passes above 4,000 m and descend into the Amazon basin subtropical zone",
    "Camp at the Inca site of Espiritu Pampa — thatched roofs still on some of the Inca buildings",
    "Trek the seldom-walked northern Inca road connecting Vilcabamba to the Apurimac",
    "Overnight in Quechua communities with mule arrieros and cook meals over a wood fire",
  ],
  "seed-adventure-949": [
    "Drive from Aviemore and hike the Lairig Ghru Pass at 835 m — the pass between the Cairngorm and Braeriach massifs",
    "Winter-walk on the Cairngorm Plateau — Scotland's largest arctic plateau above 1,200 m",
    "Navigate across the Mòine Mhòr bog in full winter kit with map and compass",
    "Climb Ben Macdui at 1,309 m — Scotland's second highest — via the Sron Riach ridge on winter snow",
    "Descend the Hell's Lum Coire by headtorch in winter dark and bivouac at the Corrour Bothy",
  ],
  "seed-adventure-950": [
    "Fly to La Paz and acclimatise at 3,600 m before starting the trek from Urmiri thermal springs",
    "Trek the classic Cordillera Real circuit passing Mururata, Huayna Potosi and Chearoco peaks",
    "Camp on the Condoriri massif lake at 4,700 m below Bolivia's most photogenic peak",
    "Attempt the Huayna Potosi summit at 6,088 m — Bolivia's most accessible 6,000 m peak",
    "Cross the Palcoco Pass at 5,300 m with views over Lake Titicaca",
    "Overnight at a community lodge in Milluni and eat quinoa stew prepared by Aymara villagers",
  ],
  "seed-adventure-951": [
    "Hike from Gjendesheim along the Knutshø ridge — the famous Peer Gynt route above the fjord",
    "Walk the Besseggen Ridge — a knife-edge arête with Gjende Lake on one side and Bessvatnet on the other",
    "Trek to Glitterheim Hut below Glittertind at 2,452 m — Norway's second highest summit",
    "Scramble Galdhøpiggen at 2,469 m — the highest peak in Scandinavia — via the east face",
    "Descend through the Svellnosbreen glacier tongue and overnight at Juvasshytta",
    "Walk to Bygdin Lake and take the boat ferry between the hut stages",
  ],
  "seed-adventure-952": [
    "Trek from Govindghat through the Bhyundar Valley to the Valley of Flowers",
    "Enter the valley on day three — 87 km² of Himalayan meadow with 300 species of alpine flower",
    "Spot snow leopard spoor on the upper meadow above 3,500 m",
    "Trek to the Hemkund Sahib Sikh shrine at 4,329 m — a glacial lake surrounded by seven snow peaks",
    "Walk the full length of the valley and photograph Himalayan monal pheasant at dawn",
    "Return via the Niti Valley and overnight at the Badrinath pilgrimage town",
  ],
  "seed-adventure-953": [
    "Begin at Cape Naturaliste lighthouse and walk the karri forest coastal trail to Cape Leeuwin",
    "Walk the Ngilgi Cave karst trail and descend into a cavern of stalactite formations",
    "Hike Wilyabrup Sea Cliffs — 60 m granite sea cliffs above the Indian Ocean surf",
    "Camp at Hamelin Bay and spot rays feeding in the shallows at the boat ramp",
    "Walk the Beach Walk section through the Leeuwin-Naturaliste National Park heath",
    "Arrive at Cape Leeuwin — where the Indian and Southern Oceans meet — and touch the lighthouse stone",
  ],
  "seed-adventure-954": [
    "Fly to Kigoma and take a lake ferry south to Mahale Mountains National Park",
    "Trek into the Mahale forest with a ranger to locate the M Group — 60 habituated chimpanzees",
    "Sit within three metres of a chimpanzee family in the undergrowth for the permitted hour",
    "Watch a dominant male display — charging and slapping buttress roots in the forest clearing",
    "Hike to the Nkungwe summit at 2,462 m — the park's highest point with views over Lake Tanganyika",
    "Swim in Lake Tanganyika — the world's second deepest lake and a centre of cichlid evolution",
  ],
  "seed-adventure-955": [
    "Trek the O-Circuit from Paine Grande Hut anti-clockwise through the back of the massif",
    "Hike the W section's Mirador Base Torres — granite towers rising 2,500 m from the Patagonian pampa",
    "Cross the John Gardner Pass at 1,241 m — the high point of the circuit with glacier views",
    "Camp at Dickson Lake in the park's remote northern sector — rarely visited by day hikers",
    "Hike the Grey Glacier viewpoint and kayak to the calving ice front",
    "Trek the Paine Valley through lenga beech forest with guanacos and condors above",
  ],
  "seed-adventure-956": [
    "Trek from Beni through the Myagdi Gorge — one of the deepest gorges in Nepal",
    "Cross the French Pass at 5,360 m and camp at the hidden Yak Kharka meadow",
    "Trek to the Dhaulagiri base camp at 4,750 m below the south pillar",
    "Cross the Dhaulagiri Icefall section roped together with crampons",
    "Camp on the Chhonbardan Glacier below the Dhaulagiri massif",
    "Traverse to the Hidden Valley at 5,100 m — a remote plateau surrounded by 7,000 m peaks",
    "Descend via Marpha and Jomsom through the Kali Gandaki apple orchards",
  ],
  "seed-adventure-957": [
    "Drive from Fort Dauphin to Isalo and enter the park at the Ranohira trailhead",
    "Trek through the Canyon des Makis — ringtailed lemurs leaping through lemur-eye-level sandstone",
    "Swim in the Piscine Naturelle — a clear natural pool fed by a waterfall in a sandstone gorge",
    "Hike to the Window of Isalo — a natural rock arch at sunset with Madagascar plateaux in silhouette",
    "Camp at the Namaza site and hear the call of sportive lemurs and nightjars",
  ],
  "seed-adventure-958": [
    "Cycle from Cape Town along the N2 coastal road past Hermanus — world's best land-based whale watching",
    "Ride the Hemel-en-Aarde Valley between vineyards growing pinot noir above the whale coast",
    "Pedal the Montagu and Outeniqua mountain passes on the Garden Route between George and Knysna",
    "Cycle the Knysna Heads — headlands rising 300 m above the estuary where otters fish at low tide",
    "Ride through the Tsitsikamma forest — home to 1,000-year-old yellowwood trees and Cape clawless otters",
    "End in Port Elizabeth with a descent to the Addo Elephant Park below the Winterberg",
  ],
  "seed-adventure-959": [
    "Fly to Samarinda and boat up the Mahakam River into the Kayan Mentarang National Park",
    "Trek a 12-day circuit through the interior with a Dayak Kenyah guide",
    "Spot wild orangutan nests in the canopy along the Bahau River tributary",
    "Visit the Apo Kayan highlands — a Dayak community with no road access",
    "Navigate the Iwan River rapids by dugout canoe through class III white water",
    "Sleep in a Dayak longhouse at Long Nawang and witness a traditional ngajat dance",
    "Trek to the border ridge at 1,800 m — looking into Sarawak, Malaysia, from the peak",
  ],
  "seed-adventure-960": [
    "Skin from Val d'Isère through the Vanoise National Park toward Bonneval-sur-Arc",
    "Cross the Col de la Leisse at 2,758 m — the heart of the Vanoise with its ibex population",
    "Overnight at the Refuge du Plan du Lac at 2,364 m and ski the Doron de Termignon",
    "Traverse the Col de la Rocheure into the Haute Maurienne valley",
    "Ski the Iseran couloirs back toward the Tarentaise valley on the final day",
    "Spot Eurasian lynx tracks in the snow near Termignon — Vanoise has France's only confirmed lynx territory",
  ],
  "seed-adventure-961": [
    "Trek from Cabanaconde village down 1,200 m into the second deepest canyon on Earth",
    "Cross the canyon floor at Sangalle — 'The Oasis' — an open air camp with pool and palm trees",
    "Hike the far side of the canyon to the remote village of Tapay accessible only by foot or mule",
    "Watch Andean condors catch thermals above the Mirador Cruz del Condor at 3,300 m",
    "Ascend the canyon via the zigzag trail and return in the first hours of daylight",
  ],
  "seed-adventure-962": [
    "Depart from M'Hamid El Ghizlane on camelback into the Erg Chegaga dune sea",
    "Sleep in a Berber goat-hair tent under the Sahara stars — absolute silence and darkness",
    "Watch the sun rise over the 150 m dunes as shadows reveal every ripple in the sand",
    "Visit a nomadic caravan well shared by Tuareg families herding their dromedar",
    "Arrive at Erg Chebbi and climb Dune Merzouga for a full view of Morocco's highest dune field",
  ],
  "seed-adventure-963": [
    "Drive to the Sepilok Orangutan Rehabilitation Centre and observe semi-wild orangutans at the feeding platform",
    "Trek the Tabin Wildlife Reserve for the critically endangered Bornean pygmy elephant",
    "Search the Kinabatangan River by boat for proboscis monkeys, hornbills and Borneo pygmy elephants",
    "Visit the Bornean Sun Bear Conservation Centre — the world's only sun bear rescue centre",
    "Night walk in the Danum Valley and spot the tarsier — the world's only carnivorous primate — by torchlight",
    "Track wild orangutan in primary rainforest with a Borneo Rainforest Lodge guide",
    "Observe the Kinabatangan floodplain by kayak in the early morning mist",
  ],
  "seed-adventure-964": [
    "Cycle from Bruck an der Glocknerstrasse up the Grossglockner High Alpine Road — 36 hairpins",
    "Climb to the Kaiser-Franz-Josefs-Höhe at 2,369 m and look across to Grossglockner at 3,798 m",
    "Descend the Fuscher Törl pass on the steepest road section in the Austrian Alps",
    "Cross into Carinthia via the Hochtor Tunnel and descend to Heiligenblut village",
  ],
  "seed-adventure-965": [
    "Trek from Koto village into the restricted Nar Phu Valley on a special permit",
    "Walk through the medieval fortified village of Phu Gaon — an enclosed Tibetan-style village at 4,080 m",
    "Cross the Kang La at 5,322 m connecting the Nar and Phu circuits",
    "Visit the Nar village monastery — an active Tibetan Buddhist monastery with 400-year-old thangka paintings",
    "Trek the Pangri La at 4,600 m with views of Annapurna II and Pisang Peak",
    "Overnight in a Nar Phu household and eat tsampa (roasted barley flour) broth with yak butter",
  ],
  "seed-adventure-966": [
    "Drive from Reykjavik along the South Coast to Seljalandsfoss — walk behind the 60 m curtain waterfall",
    "Continue to Skógafoss and climb the 527 steps to the cliff top for a rainbow at the falls",
    "Drive to the Jökulsárlón Glacier Lagoon — icebergs calved from Breiðamerkurjökull floating to the sea",
    "Watch the Diamond Beach — black sand strewn with ice sculptures at the lagoon outlet",
    "Stop at Dyrhólaey — the sea arch and puffin colony at the tip of the South Coast headland",
  ],
  "seed-adventure-967": [
    "Fly to Sandspit on Haida Gwaii and paddle from Queen Charlotte toward Gwaii Haanas National Park Reserve",
    "Kayak through the Anthony Island World Heritage Site — the ancient Haida village of Sgang Gwaay",
    "Observe the totem poles of K'úuhl — 19 monumental poles still standing in the rainforest",
    "Camp on a Haida Gwaii beach and spot black bears hunting for spawning salmon",
    "Paddle the Burnaby Narrows — the world's highest density of intertidal invertebrates",
    "Cross Juan Pérez Sound in open water to Rose Harbour on the south island",
    "Spot Pacific white-sided dolphins, Steller sea lions and humpback whales on the open crossing",
  ],
  "seed-adventure-968": [
    "Fly to Mongu and drive into Liuwa Plain — the second largest wildebeest migration in Africa",
    "Watch 30,000 wildebeest moving across the open floodplain in October and November",
    "Track the resident lion family on foot with a Frank's Liuwa Camp guide",
    "Spot the critically endangered African wild dog pack denning on the Liuwa Plain",
    "Walk the floodplain at dawn with only the sound of wildebeest and the sky blazing with migrants",
    "Canoe the Luambimba River through lilies and hippo pods",
  ],
  "seed-adventure-969": [
    "Fly to Sapporo and take the train to Asahikawa — gateway to the Daisetsuzan central wilderness",
    "Skin from the Kurodake ropeway and tour the summit plateau above the treeline",
    "Camp at the Hokkaido Backcountry Snowcamp hut at 1,400 m",
    "Ski the north-facing Chubetsu valley — untracked powder in a forest of Japanese white birch",
    "Tour to the Tomuraushi mountain hut and ski the summit couloir — a 45° aspect in powder",
    "Soak in the Sounkyo Gorge onsen below the frozen basalt columns of the Daisetsuzan walls",
  ],
  "seed-adventure-970": [
    "Fly from Kathmandu to Juphal and trek north into the remote Dolpo district",
    "Cross the Numa La pass at 5,190 m into the Upper Dolpo restricted area",
    "Trek to the sacred Phoksundo Lake — Nepal's deepest lake at 3,611 m — a vivid turquoise",
    "Visit the Crystal Mountain and the Shey Gompa monastery — Tibetan Buddhism's most remote site",
    "Cross the Saldang La at 5,093 m between the Inner Dolpo valleys",
    "Trek through ancient Bon monastery villages where animist Tibetan religion predates Buddhism",
    "Cross the Kagmara La at 5,115 m and descend to Juphal through rhododendron forest",
  ],
  "seed-adventure-971": [
    "Embark from Lyttelton, New Zealand, and sail south through the Subantarctic islands",
    "Zodiac-land at Campbell Island and walk among 7,000 southern royal albatrosses at close range",
    "Cross the Antarctic Circle and push into the Ross Sea — the world's most pristine marine ecosystem",
    "Visit Cape Adare — the first landing site on Antarctica's continental coast",
    "Walk among 250,000 Adélie penguin pairs at the world's largest penguin colony at Cape Adare",
    "Helicopter to the Ross Ice Shelf edge — standing on a slab of floating ice 800 km wide",
    "Visit Scott's Terra Nova Hut at Cape Evans — frozen in time since 1911",
  ],
  "seed-adventure-972": [
    "Hike to the Ranu Raraku quarry — where 950 moai statues were carved from tuff before transport",
    "Walk the coastal trail from Anakena to Ahu Tongariki — 15 moai restored in a line above the ocean",
    "Cycle the island perimeter — 60 km of coastal road with ahu (ceremonial platforms) at every headland",
    "Climb Rano Kau volcano crater — a flooded caldera with floating reed islands",
    "Visit the ceremonial village of Orongo — Birdman Competition site on the crater rim",
    "Kayak offshore from Anakena Beach and see the moai from sea level at sunset",
  ],
  "seed-adventure-973": [
    "Trek north from Abisko through the Björkliden birch forest — the Swedish Lapland gateway",
    "Cross the Tjäktja Pass at 1,140 m — the highest point on the Kungsleden and the route's main challenge",
    "Camp at Sälka with the Sarek Massif filling the eastern skyline",
    "Hike the Nallo summit day — a scramble to 1,751 m with views of Kebnekaise and the Norwegian border peaks",
    "Canoe across the Teusajaure and Akkajaure lakes — mandatory crossing at the midpoint",
    "Walk the final birch and willow floodplain to Kvikkjokk and celebrate at the mountain hotel",
  ],
  "seed-adventure-974": [
    "Trek from Nelong Valley in Uttarkashi north toward the Tibetan border",
    "Walk the high-altitude section of the Great Himalayan Trail from Har Ki Dun at 3,566 m",
    "Cross the Rupin Pass at 4,650 m connecting the Baspa and Tons valleys",
    "Trek through the Govind Pashu Vihar National Park — a protected high-altitude wilderness",
    "Overnight in the remote shepherds' summer village of Osla above 3,000 m",
    "Descend via the Tons River valley through the deodar cedar forest to Sankri",
  ],
  "seed-adventure-975": [
    "Rent a motorbike in Hanoi and head northwest toward Hoa Binh and Son La",
    "Ride the Pha Din Pass at 1,648 m — the most feared pass in Vietnam's northwestern campaign",
    "Navigate the Tay Bac roads past terraced rice fields and Hmong villages above 1,500 m",
    "Cross into Lai Chau province and ride to the Sinho market — a Sunday minority market in the hills",
    "Descend to Dien Bien Phu and visit the battle sites of the 1954 Siege",
    "Ride the Ma Pi Leng circuit back east via Ha Giang and the Dong Van Plateau",
  ],
  "seed-adventure-976": [
    "Embark from Stanley, Falkland Islands, and sail southeast for South Georgia",
    "Zodiac-land at Salisbury Plain among 250,000 king penguins — the world's second largest colony",
    "Hike to the Shackleton Gap — the pass Ernest Shackleton crossed in 1916 on the survival march",
    "Visit the Shackleton Memorial and the grave at Grytviken whaling station",
    "Observe elephant seal bulls fighting on the beaches of Gold Harbour",
    "Zodiac into the calving front of the Neumayer Glacier at close range",
    "Return via the Falklands and watch black-browed albatross colonies at Saunders Island",
  ],
  "seed-adventure-977": [
    "Trek from Arughat Bazaar into the Tsum Valley — a Tibetan Buddhist enclave hidden behind the Ganesh Himal",
    "Walk the Tsum circuit through Chumling, Mu Gompa and Nile — villages unchanged for centuries",
    "Visit the Mu Gompa monastery — a 1,000-year-old walled monastery on a cliff at 3,700 m",
    "Cross the Ngula Dhoja Pass at 5,093 m into the upper Tsum circuit",
    "Stay with Tsumba families in stone-walled houses decorated with hand-painted mandalas",
    "Spot Himalayan blue sheep, Himalayan tahr and snow leopard tracks on the high ridges",
    "Return via the Ganesh Himal Base Camp route and overnight at Deng village",
  ],
  "seed-adventure-978": [
    "Drive from Bariloche to the Villa La Angostura ski area — a small resort on the Nahuel Huapi shore",
    "Ski the Cerro Bayo backcountry and cross into the Chapelco resort on the Pehuenche Pass tour",
    "Ski across the volcanic plateau of the Parque Nacional Nahuel Huapi on groomed tracks",
    "Overnight at the Refugio Otto Meiling at 2,000 m below the south face of Tronador",
    "Ski the Paso de las Nubes route — a 3-day crossing from Pampa Linda to Puerto Frías",
    "Descend to the Peulla border post on the Chilean side and return by catamaran on Lago Todos los Santos",
  ],
  "seed-adventure-979": [
    "Drive from Dalanzadgad into the South Gobi Desert on a camel-loaded expedition vehicle",
    "Mount Bactrian camels and trek south into the Khongoryn Els dune sea — the 'Singing Sands'",
    "Camp in a ger at the base of 200 m dunes and hear the booming resonance of the sand at dawn",
    "Trek to the Yol Am Ice Canyon — a frozen gorge that retains ice year-round in the desert",
    "Visit the Flaming Cliffs of Bayanzag — where Roy Chapman Andrews found the first dinosaur eggs in 1922",
    "Stay with a Gobi nomad family and practice the Mongolian wrestling traditions",
  ],
  "seed-adventure-980": [
    "Bus to Manning Park and hike the Cascade Lookout into the Coast Mountains backcountry",
    "Traverse the Skagit Valley headwaters across the Cascade divide",
    "Trek the Skyline Trail and camp at Dewdney Trail Pass on the US border ridge",
    "Climb the Cathedral Peak ridge above Cathedral Lake and descend to Princeton",
    "Navigate the Coquihalla summit section on unmarked alpine terrain",
    "Descend to Pemberton via the Tenquille Lake route above the Lillooet Valley",
  ],
  "seed-adventure-981": [
    "Fly to Kilimanjaro and enter the Serengeti via the western corridor from Musoma",
    "Drive the Grumeti River crossing in June — crocodile-filled waters and the waiting migration",
    "Follow the 1.5 million wildebeest and 250,000 zebra on the northern circuit in July-August",
    "Watch the Mara River crossing from the Tanzanian side — hundreds of wildebeest at once",
    "Night game drive with a spotlight for leopard, caracal and genet cat on the kopjes",
    "Fly-camp under the stars on the open Serengeti plains — dinner with lion audible at 500 m",
  ],
  "seed-adventure-982": [
    "Cycle from Garmisch to Brenner Pass on the Transalpine Route — 750 km across three Alpine ranges",
    "Climb the Fernpass at 1,209 m on the Austrian-German border amid limestone peaks",
    "Descend the Reschen Pass into the South Tyrol — Italian-speaking but German in culture",
    "Ride along Lake Reschen where a church tower rises from the lake surface — drowned in 1950",
    "Cross the Brenner Pass at 1,374 m — the lowest Alpine pass — into the Bolzano lowlands",
    "End in Riva del Garda on Lake Garda, 700 m below the Dolomite escarpment",
  ],
  "seed-adventure-983": [
    "Fly to Mount Hagen and drive to the Wahgi Valley — home of the Highland tribes",
    "Attend the Goroka Show — thousands of warriors in full traditional dress with feather headdresses",
    "Trek into the Jiwaka Valley and visit a Kuma community house for a traditional pig feast",
    "Hike to the Tambul River headwaters and spend two nights in the Highlands fog forest",
    "Visit a sing-sing preparation — body painting, necklace stringing, and feather headdress assembly",
    "Overnight in a Highland guesthouse and eat sweet potato and roka greens prepared in a mumu pit",
  ],
  "seed-adventure-984": [
    "Fly to Tehran and collect the touring bike for the desert crossing east",
    "Cycle through Kashan — the City of Roses — and visit the 7th-century Friday Mosque",
    "Cross the Dasht-e Kavir edge to Yazd — a UNESCO mudbrick city with Zoroastrian fire temples",
    "Ride the Silk Road highway through Meybod and Ardakan to the Yazd Desert",
    "Visit the Towers of Silence — Zoroastrian sky burial sites on a hill above the desert",
    "Cycle into the Lut Desert — the hottest recorded surface temperature on Earth at 70.7 °C",
    "End in Kerman and visit the bazaar — the longest covered bazaar in the world",
  ],
  "seed-adventure-985": [
    "Fly to Bogotá and take a charter to La Macarena at the edge of the Amazon foothills",
    "Trek to the Caño Cristales River — the 'liquid rainbow' with red, yellow, blue and green algae",
    "Walk the river from Corcovado pool to the Toboganes waterfalls — clearest water in Colombia",
    "Swim in the Los Ochos natural pools carved into the red rock by the current",
    "Overnight in La Macarena — the closest town to one of Colombia's most spectacular natural wonders",
  ],
  "seed-adventure-986": [
    "Fly to Talkeetna and ski by bush plane to Kahiltna Base Camp at 2,240 m on the glacier",
    "Carry loads to Camp 1 at 3,350 m through the Kahiltna Glacier lower icefall",
    "Climb the West Buttress to Camp 3 at Genet Basin (4,334 m) and acclimatise",
    "Push to High Camp (5,240 m) and wait for a weather window on the upper mountain",
    "Summit day: from High Camp to Denali's summit at 6,190 m — North America's highest peak",
    "Descend the full route in a single push and ski back to base camp",
    "Fly off the glacier to Talkeetna for moose stew and beer at the Latitude 62 Lodge",
  ],
  "seed-adventure-987": [
    "Paddle sea kayaks from Cagliari south and follow the Sardinian coast through the Sulcis sea caves",
    "Sea kayak through the sea arch of Capo Pecora — a 40 m natural tunnel above the Mediterranean",
    "Camp on the uninhabited Isola di San Pietro and swim in the tuna fishing village harbour",
    "Paddle north via the Bue Marino caves — monk seal habitat and accessible only by kayak",
    "Navigate the Orosei Gulf sea caves on the east coast — Le Grotte del Bue Marino",
    "Snorkel the Cala Goloritzé beach — a UNESCO natural monument accessible only from the sea",
    "Cross from Alghero to the Asinara National Park island — a maximum security prison until 1997",
  ],
  "seed-adventure-988": [
    "Fly to Nepalgunj and connect to Juphal airstrip, then trek north into the Shey Phoksundo National Park",
    "Walk the Tarap Valley — a high trans-Himalayan corridor connecting Dolpo to Tibet",
    "Trek through the Ringmo village above Phoksundo Lake — a Bon community with ancient practices",
    "Reach Phoksundo Lake — Nepal's deepest lake at 145 m — in deep turquoise",
    "Hike to the waterfall and the gompa on the lake's edge — a cliff monastery above the water",
    "Trek the Phoksundo Khola gorge to the restricted inner Dolpo border",
    "Return via the Kagmara Pass at 5,115 m and descend to Juphal through pine forest",
  ],
  "seed-adventure-989": [
    "Drive from Nairobi to the Chyulu Hills — volcanic hills rising from the Amboseli savanna",
    "Walk the Chyulu Hills on foot with a Maasai guide in the cloud forest of the lava field",
    "Descend into the Leviathan Cave — a 12 km lava tube, the world's second longest",
    "Camp at the Ol Donyo Lodge with Mount Kilimanjaro reflected in the evening watering hole",
    "Track elephants through the Kimana Corridor — the migration path between Amboseli and Tsavo",
    "Night watch at a waterhole platform for leopard and spotted hyena",
  ],
  "seed-adventure-990": [
    "Train to Rovaniemi and collect skis for the Lapland crossing north",
    "Ski across Finland's Lake District on marked wilderness ski trails through birch forest",
    "Cross the Finnish-Norwegian border on skis at Utsjoki — following the frozen Tana River",
    "Push north on the Finnmarksvidda — the largest uninhabited wilderness in Europe",
    "Ski through the Sami winter reindeer herding grounds guided by a Sami elder",
    "Reach the North Cape plateau at 71°N — the most northerly point in continental Europe",
    "Celebrate with a flame in a traditional Sami lavvu tent and reindeer stew",
  ],
  "seed-adventure-991": [
    "Drive from Iringa into Ruaha National Park through the combretum-bushwillow woodland",
    "Night drive with a spotlight on the Mwagusi Sand River searching for leopard and lion",
    "Walk the Ruaha escarpment with an armed ranger watching a honey badger dismantle a bees' nest",
    "Lie on a camp cot outside and watch the Southern Cross wheel over the Milky Way",
    "Photograph the elephant herds silhouetted against the Great Ruaha River at sunset",
    "Listen to the lion roar answered from three compass points at midnight",
  ],
  "seed-adventure-992": [
    "Canoe into the Quetico Provincial Park Wilderness from the Dawson Trail launch point",
    "Portage 26 km of trails linking the Quetico lake chain into the interior",
    "Fish for walleye and lake trout in Sturgeon Lake — minimal boat traffic, no motors allowed",
    "Camp on a granite outcrop above a lake with loon calls echoing at dawn",
    "Navigate a chain of 12 linked lakes on the central route using topo map only",
    "Paddle the French Lake exit and return to Atikokan on the final day",
  ],
  "seed-adventure-993": [
    "Fly to Funchal and hike the Levada do Caldeirão Verde — a 17 km irrigation channel trail through laurisilva",
    "Walk through the Fanal ancient laurel forest — 500-year-old til trees in permanent mist",
    "Hike the PR1 Vereda do Areeiro — summit link between Pico Ruivo (1,861 m) and Pico do Areeiro",
    "Walk the levada along the north coast cliffs of the Encumeada Pass to São Vicente",
    "Swim in the natural tidal pools of Porto Moniz — volcanic rock formations on the northwest coast",
  ],
  "seed-adventure-994": [
    "Trek from Soti Khola through the sub-tropical lowland jungle into the Manaslu Conservation Area",
    "Cross the Larkya La at 5,213 m — the circuit's highest point — on day 14",
    "Camp at Samdo at 3,860 m in a Tibetan-style village with views of the Himalayan border peaks",
    "Walk through Namrung and Syala with their medieval Buddhist gompas and mani walls",
    "Acclimatise at Bimthang (3,590 m) before the Larkya La final approach",
    "Descend via Dharapani to the Annapurna Circuit for the bus to Besisahar",
  ],
  "seed-adventure-995": [
    "Drive from La Paz to Potosí at 4,090 m — once the world's most populated city in 1600",
    "Descend into the Cerro Rico mine with a miner guide — tin and zinc extraction still ongoing",
    "Walk the colonial cobblestone streets past 86 Baroque churches and the Casa de la Moneda",
    "Trek into the Cordillera de Chichas on the Altiplano plateau east of Potosí",
    "Overnight at a Quechua community and participate in a traditional blessing ceremony",
  ],
  "seed-adventure-996": [
    "Drive from Springbok to the Richtersveld National Park — a volcanic moon landscape above the Orange River",
    "Canoe the Orange River through the canyon — 4 days of paddling in the Klipspringer Gorge",
    "Hike the Vensterval Trail through the quiver tree forest on the canyon rim",
    "Rock-climb the Corniskop volcanic plug — 250 m of trad climbing above the river",
    "Walk through the Richtersveld halfmens succulent forest — tree aloes unique to this canyon",
  ],
  "seed-adventure-997": [
    "Sail from Labuan Bajo by private phinisi boat east toward the Flores Sea",
    "Dive the Batu Bolong seamount — grey reef sharks circling at 25 m in a current-swept channel",
    "Anchor off the Pink Beach and snorkel the coral bommies with turtles feeding at 5 m",
    "Sail through the night to Flores and trek to the Kelimutu three-coloured crater lakes",
    "Snorkel the Manta Point near Wan Ela for manta rays gliding over the cleaning station",
  ],
  "seed-adventure-998": [
    "Take the bangka from Dauin to Apo Island — a marine sanctuary closed to fishing since 1986",
    "Dive the 'Chapel' site for a turtle cleaning station — green turtles hovering as fish remove parasites",
    "Freedive the west wall to 20 m where the reef drops into the Pacific",
    "Snorkel the north shore with 650 fish species documented in a 0.7 km² reef",
    "Practise freediving technique on the buoy line with a local Dauin freediving instructor",
  ],
  "seed-adventure-999": [
    "Fly to Lukla (2,860 m) and begin the classic route through Phakding and Namche Bazaar",
    "Acclimatise at Namche for two nights — visit the Sherpa Museum and the Saturday market",
    "Trek through Tengboche Monastery at 3,867 m as the sun hits Ama Dablam's east face",
    "Pass through Pheriche and Lobuche and arrive at Gorak Shep (5,164 m) for base camp day",
    "Hike to Everest Base Camp at 5,364 m and look up at the Khumbu Icefall",
    "Summit Kala Patthar at 5,644 m at dawn for the highest viewpoint on the trek",
    "Descend to Lukla over three days through the lower Dudh Kosi gorge",
  ],
  "seed-adventure-1000": [
    "Arrive in Chamonix and acclimatise on the Aiguille du Midi cable car at 3,842 m",
    "Trek to the Goûter Hut (3,835 m) via the Tête Rousse Hut — the standard route's halfway point",
    "Cross the Grand Couloir — a 200 m rockfall zone typically crossed before 5 am",
    "Night at the Goûter Hut and summit push from 11pm — the final 1,000 m in darkness",
    "Summit Mont Blanc at 4,808 m — the highest point in the Alps and all of Western Europe",
    "Descend the summit ridge in full crampons and return to Chamonix by afternoon",
  ],
};

async function main() {
  const ids = Object.keys(HIGHLIGHTS);
  console.log(`Backfilling highlights for ${ids.length} adventures (batch 2)...`);

  let updated = 0;
  for (const id of ids) {
    const highlights = HIGHLIGHTS[id];
    await prisma.adventure.update({
      where: { id },
      data: { highlights },
    });
    updated++;
    if (updated % 20 === 0) console.log(`  ${updated}/${ids.length}`);
  }

  console.log(`Done — updated ${updated} adventures`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
